### ISSUE TITLE
Harmonizing SVG needs to make path data consistent

### ISSUE THREAD

**Issue by leehericks** [KanjiVG/kanjivg#100]
The last time I ran my Obj-C SVG path parser on the newest KanjiVG release, it kept crashing and I found myself adding code and checks for spaces, commas, and minuses to parse the path commands because they are not all stored in the same way(multiple editors?). I know there are spacious and terse options for SVG path data, but I think we ought to decide an easy to parse format, like guaranteeing a space before a negative number so that someone can simply split the string by white spaces and step through the tokens to find commands and following numbers.

Additionally, it would not hurt to calculate and fill in the pathLength attribute during harmonization as recommended in section 8.4, "Distance along a path".  Perhaps I can port my Obj-C classes to Python.  While I'm not using SVG in my projects, the pathLength attribute may affect people using KanjiVG as SVG and using animations.

**Comment by Gnurou** [comment]
I agree that a parser should be able to handle any valid input and not a "convenient" subset. On the other hand, maybe it is a mistake to use SVG as the base format for KanjiVG. We need to replicate all the headers, which results in a lot of non-active code in the files, XML is cumbersome to read for humans, and the current format is not even convenient for all uses.

Maybe a simplified and extensible format, describing the strokes and the groups separately (and potentially containing other data such as SKIP information), and from which we could easily generate other formats (including the current SVG) would be better? This is a leading question as I am now convinced it would be, but we would need to define it and write the tools to manipulate it.

I am still dreaming of a web-based WYSIWYG editor that would allow fixes to be done easily and immediately commited to Github. This would lower the bar for participation greatly.

**Comment by Gnurou** [comment]
Oh and also (sorry to throw raw ideas like this), a new format should limit the amount of redundant data, to avoid repeating the structure of a component when it is the same for all its instances.

**Comment by Kazetsukai** [comment]
I like this idea, having a different base format that is easier to parse (maybe some XML still) that can be turned into SVG. Even with a quick glance I noticed there were different combinations of relative and absolute coordinates being used for the bezier curves depending on the file.

Also that WYSIWYG editor idea is interesting, I wonder how advanced of a vector graphics tool it would need to be? Is support for cubic beziers and the structure defined by KanjiVG enough?

**Comment by benkasminbullock** [comment]
While I do sympathise with the problems, having authored [an SVG path parser](https://metacpan.org/dist/Image-SVG-Path), and basically any format whatsoever picked at random would probably be an improvement over SVG paths, be assured that the SVG path data in KanjiVG complies with the [SVG path specifications](https://www.w3.org/TR/SVG/paths.html). I think this issue should be closed, but please reopen if not satisfied.
