### ISSUE TITLE
祭 stroke 5 should be longer through stroke 6

### ISSUE THREAD

**Issue by rasteps** [KanjiVG/kanjivg#104]
Stroke 5 should cut across stroke stroke 6 to look more like 又

**Comment by Gnurou** [comment]
Looks like this depends on the font ; I can certainly find plenty where stroke 5 is the same length as what we have.

**Comment by ospalh** [comment]
This [official list](http://www.bunka.go.jp/kokugo_nihongo/pdf/jouyoukanjihyou_h22.pdf)(PDF, it’s from the government) shows two variants of this, (page 5, point (4)) with stroke 5 touching stroke 6 and with stroke 5 crossing stroke 6 by just a little bit. The way this is now.

Etymologically those two strokes seem to be a 又, but this is a variant with that stroke shorter to make room for the 示 below.

**Comment by ospalh** [comment]
I did notice that the kanji with this element didn’t all have this stroke in the same style.
See #105.
