### ISSUE TITLE
丰 and 夆

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#116]
丰 is referenced as a  component a few times, but it looks like it is missing as a standalone character.
夆 can be seen as a component as well and has a codepoint, so i guess it could be added to kanji like 蜂, 峰 and 鋒 as a grouping and as a standalone character.

**Comment by looki** [comment]
I just noticed this as well. There are more instances of this issue: 峯 烽 篷 蓬 蜂 逢 鋒

**Comment by benkasminbullock** [comment]
To clarify, 丰 is not part of the JIS level one/two kanji so it's not in this repo.
