### ISSUE TITLE
XML file is missing namespace

### ISSUE THREAD

**Issue by BlueRaja** [KanjiVG/kanjivg#118]
I'm using the .xml.gz file from [here](https://github.com/KanjiVG/kanjivg/releases).  That file is missing the declaration of the `kvg` namespace.  It's causing `invalid XML` errors to be thrown when I try to parse it using an XML parser.

Note that the files in the `-main.zip` file do not have this problem.  They correctly declare their namespace using

	<!ATTLIST g
	xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
	kvg:element CDATA #IMPLIED
	kvg:variant CDATA #IMPLIED
	kvg:partial CDATA #IMPLIED
	kvg:original CDATA #IMPLIED
	kvg:part CDATA #IMPLIED
	kvg:number CDATA #IMPLIED
	kvg:tradForm CDATA #IMPLIED
	kvg:radicalForm CDATA #IMPLIED
	kvg:position CDATA #IMPLIED
	kvg:radical CDATA #IMPLIED
	kvg:phon CDATA #IMPLIED >
	<!ATTLIST path
	xmlns:kvg CDATA #FIXED "http://kanjivg.tagaini.net"
	kvg:type CDATA #IMPLIED >

_(At least, I assume it is correct - I'll admit I'm not an XML-namespaces expert...)_

**Comment by ospalh** [comment]
You are the second one to complain about this in two weeks.
Anyway, please use the version from the [newest release](https://github.com/KanjiVG/kanjivg/releases/tag/r20150615).

**Comment by BlueRaja** [comment]
Sorry, I did not think to check the closed issues for open issues.

**Comment by ospalh** [comment]
> Sorry, (…)

I just meant it as an observation, no need to apologize. The version with the namespace wasn’t released, so reporting this was fine, and it actually made me do the release a bit earlier.

**Comment by BlueRaja** [comment]
Awesome, thank you!!
