### ISSUE TITLE
Unparsable XML

### ISSUE THREAD

**Issue by mvysny** [KanjiVG/kanjivg#119]
Hi, thank you very much for your great work. I am machine-parsing the XML downloaded from https://github.com/KanjiVG/kanjivg/releases/download/r20150615/kanjivg-20150615.xml.gz
The XML parser fails: lineNumber: 10204; columnNumber: 59; Element type "g" must be followed by either attribute specifications, ">" or "/>".
<g id="kvg:051b3-g1" kvg:element="冫" kvg:position="left" "水" kvg:radical="tradit">
The "水" is not assigned to any attribute.

**Comment by leoboiko** [comment]
Sorry! In the future, I'll make sure to xmllint all files before commiting.

**Comment by mvysny** [comment]
No problem, thank you for such a quick fix.

**Comment by ospalh** [comment]
Please try the [updated release](https://github.com/KanjiVG/kanjivg/releases/tag/r20150615-2).
This time i tried loading it into a Python ElementTree, and it worked better than the first try.
