### ISSUE TITLE
祭 Etymology

### ISSUE THREAD

**Issue by wareya** [KanjiVG/kanjivg#123]
[Wiktionary](https://en.wiktionary.org/wiki/祭#Etymology) shows the etymology of the top components being ⺼ "meat" and 手 (i.e. 又) "hand". The [format](http://kanjivg.tagaini.net/format.html) page says that an "original" field should indicate the semantical purpose of a group. Should this be included, particularly since an "element" field of "moon" exists for the top-left component? Should the strokes of the top-right component be grouped together?

**Comment by benkasminbullock** [comment]
I wonder why that format page is not in this repository but only on that website.

**Comment by benkasminbullock** [comment]
It's not at all clear that the upper right part needs to have the 手 added to it. That 又 means hand, but I can't find evidence that it's an alternative form of 手. The left upper part already has element="月". The "original" field only needs to be added if there is an element which is different from the original form.

Anyway it's been seven years, so let's close this issue. Please reopen it if not satisfied.
