### ISSUE TITLE
Incorrect components for 勇 (reposted).

### ISSUE THREAD

**Issue by fontfish** [KanjiVG/kanjivg#124]
I have just copy-pasted the following from my post in the Tagaini Jisho page, though I've also added a picture from an old kanji dictionary detailing the older form of the kanji (which more clearly shows its origins).

The kanji 勇 “Brave” has the following components listed:
マ: katakana "ma"
男: male.

The correct components, as far as I am aware, are “甬” and “力”, which give pronunciation and meaning. It seems “マ” and “男” are often taught in Japanese schools but are incorrect. For clarification, I recommend taking a look at the Glyphwiki page listing traditional and variant forms of this kanji.
http://en.glyphwiki.org/wiki/u52c7

Wiktionary also lists the correct components.
https://en.wiktionary.org/wiki/%E5%8B%87

Other sources:
異体字の世界 “The World of Kanji Variants” (Japanese book)
![yuu](https://cloud.githubusercontent.com/assets/16020041/11546775/2084acfa-9947-11e5-97ef-c2ced7fcea5b.JPG)

**Comment by ospalh** [comment]
You are probably right.
Are you going to change [it](https://github.com/KanjiVG/kanjivg/blob/master/kanji/052c7.svg)?
If so, you should probably keep the ` kvg:element="田`, and add ` kvg:variant="true" kvg:original="用"`.
Also, the [kaisho variant](https://github.com/KanjiVG/kanjivg/blob/master/kanji/052c7-Kaisho.svg) and kanji that contain 勇, (湧, 踴, plus kaisho variant of 踴) should probably changed as well.

**Comment by ospalh** [comment]
Otoh, there is a [discussion](https://groups.google.com/forum/#!topic/kanjivg/8U_RVOS2ZcY) about changing the format radically. The new format would probably allow different groupings based on the shapes (マ + 男) *and* etymology (甬 + 力).
Contributions (ideas and code) are welcome.
And on both fronts, correcting the groupings and changing the format, there isn’t really anybody actively working. So, if you want something done your best bet is doing it yourself. New contributors are always welcome. :smile:

**Comment by fontfish** [comment]
Thanks for the replies. Sorry for taking so long to do so myself.

I have to admit that I am new to GitHub and have almost no knowledge of the non-graphical side of svg, so it would take a long time for me to change it myself as I'd have to do quite a bit of learning first. I'm not opposed to that, though it might be more practical in the short term if anyone has time to do a quick change. For now, I might be able to provide ideas though, and I'll take a proper look at the discussion when I can.

The kaisho variant and derivatives should probably also be changed to match if the basic 勇 is changed, yes. It seems there are swathes of books and charts detailing etymology of 漢字, so I might be able to help out with checking some of that as my Japanese progresses.

**Comment by benkasminbullock** [comment]
That decomposition is valid for Chinese but not Japanese. Top part of the character in Chinese looks like that but the Japanese one doesn't.

**Comment by fontfish** [comment]
Thanks for commenting, and my apologies for the slow reply!

Regarding ospalh's comment from 2015, was there any change in format? The last post in the link is also from 2015 … If there is a new field for etymology or a field for old or variant forms, that would allow 力 and 甬 to be clearly listed.

If the current format still only allows listing components as they are written, マ and 男 do make sense, though personally I think it might be better then to label the components as マ, 田 and 力, especially as the radical is 力 (whereas the radical for 男 is 田), as that would help to avoid confusion about etymology, traditional Chinese writing, historical and variant forms, etc.).

Please let me know your thoughts. If there's a consensus for マ and 男 or if a more complex listing would clearly contradict the aims of the component field, it's probably about time I closed this issue, though if there is a way that the component listing can be made a little clearer, I'll leave it open for now.

**Comment by benkasminbullock** [comment]
[IDS](https://github.com/cjkvi/cjkvi-ids) gives

    U+52C7	勇	⿱甬力[GTV]	⿱⿱龴田力[JK]

for this character. (Here GTV means mainland China, Taiwan, Vietnam, and JK means Japan and Korea.) KanjiVG is a Japanese kanji project, so using the Chinese decomposition would be pointless. KanjiVG does not give other etymologies or clarifications, so that justification for including the Chinese derivation doesn't seem valid. Your notion might be useful if we were talking about some kind of generalised project to cover all Chinese characters, but it doesn't seem particularly relevant considering the current state of this project.

**Comment by fontfish** [comment]
Given what you mention about the aims of KanjiVG, I now absolutely agree that giving the traditional and Chinese derivation (力 and 甬) is unnecessary, though it seems to me that IDS gives the composition as three individual components there, much like I also mentioned in my last comment.

Admittedly, I'm not entire sure whether you're saying that there is no need to do the same in KanjiVG as IDS already gives this info or not. I should maybe have been clearer about the idea of using マ, 田 and 力, as now I can't tell if that's what you're referring to when you say notion (or if you're still talking about the Chinese decomposition).

It's clear that some software takes its kanji component info from KanjiVG (such as Tagaini Jisho), though perhaps those programs should perhaps be using IDS for that info instead if they do want to give a more complete overview …

**Comment by fontfish** [comment]
Aha! I've just had a closer look at the [.svg](https://github.com/KanjiVG/kanjivg/edit/master/kanji/052c7.svg) for that character, and have noticed the following two lines:

Line 45: `<g id="kvg:052c7-g3" kvg:element="田" kvg:position="top" kvg:phon="甬V2">`
Line 52: `<g id="kvg:052c7-g4" kvg:element="力" kvg:position="bottom" kvg:radical="general">`

Kicking myself for not paying more attention to that to begin with! It seems all the information is indeed already in there, though evidently many programs aren't using it properly. I'll close this issue now, then. Thank you very much for your replies and thoughts on the matter.
