### ISSUE TITLE
⺈ character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#132]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by scriptin** [comment]
There is one kanji which has kind of "intermediate" version b/w "⺈" and "勹": [歿/06b7f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06b7f.svg)

Other than that one, here's a list of kanji which contain "⺈":

[亀/04e80.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/04e80.svg), [争/04e89.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/04e89.svg), [像/050cf.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/050cf.svg), [免/0514d.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0514d.svg), [勉/052c9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/052c9.svg), [危/05371.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05371.svg), [啗/05557.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05557.svg), [喚/0559a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0559a.svg), [夐/05910.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05910.svg), [奐/05950.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05950.svg), [巉/05dc9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05dc9.svg), [急/06025.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06025.svg), [憺/061ba.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/061ba.svg), [換/063db.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/063db.svg), [擔/064d4.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/064d4.svg), [橡/06a61.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06a61.svg), [浄/06d44.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06d44.svg), [焔/07114.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07114.svg), [瞻/077bb.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/077bb.svg), [穐/07a50.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07a50.svg), [筝/07b5d.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07b5d.svg), [脆/08106.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08106.svg), [膽/081bd.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/081bd.svg), [色/08272.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08272.svg), [艶/08276.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08276.svg), [菟/083df.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/083df.svg), [衡/08861.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08861.svg), [角/089d2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/089d2.svg), [觸/089f8.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/089f8.svg), [譫/08b6b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08b6b.svg), [象/08c61.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08c61.svg), [豫/08c6b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08c6b.svg), [負/08ca0.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08ca0.svg), [跪/08dea.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08dea.svg), [逸/09038.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09038.svg), [閻/095bb.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/095bb.svg), [陥/09665.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09665.svg), [陷/09677.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09677.svg), [静/09759.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09759.svg), [魚/09b5a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09b5a.svg), [魯/09b6f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09b6f.svg), [鯣/09be3.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09be3.svg), [鰐/09c10.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09c10.svg), [鰔/09c14.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09c14.svg), [麁/09e81.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09e81.svg)
