### ISSUE TITLE
㔾 character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#133]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by scriptin** [comment]
[卮/0536e.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0536e.svg), [危/05371.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05371.svg), [卷/05377.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05377.svg), [厄/05384.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05384.svg), [圈/05708.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05708.svg), [婉/05a49.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05a49.svg), [宛/05b9b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05b9b.svg), [怨/06028.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06028.svg), [扼/0627c.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0627c.svg), [椀/06900.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06900.svg), [氾/06c3e.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06c3e.svg), [熈/07188.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07188.svg), [犯/072af.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072af.svg), [碗/07897.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07897.svg), [笵/07b35.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07b35.svg), [範/07bc4.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07bc4.svg), [腕/08155.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08155.svg), [苑/082d1.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/082d1.svg), [范/08303.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08303.svg), [蜿/0873f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0873f.svg), [詭/08a6d.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08a6d.svg), [豌/08c4c.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08c4c.svg), [跪/08dea.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08dea.svg), [軛/08edb.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08edb.svg), [鋺/092fa.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/092fa.svg), [阨/09628.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09628.svg), [鮠/09ba0.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09ba0.svg), [鴛/09d1b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09d1b.svg)
