### ISSUE TITLE
丬 character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#134]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by scriptin** [comment]
[壮/058ee.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/058ee.svg), [奨/05968.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05968.svg), [寝/05bdd.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05bdd.svg), [将/05c06.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05c06.svg), [状/072b6.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072b6.svg), [荘/08358.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08358.svg), [蒋/0848b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0848b.svg), [装/088c5.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/088c5.svg), [醤/091a4.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/091a4.svg)

Also, there is a very similar variant - left part of 北. It has a different stroke order: first stroke is an upper horizontal one. It looks like another variant of 爿.

[乖/04e56.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/04e56.svg), [乘/04e58.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/04e58.svg), [冀/05180.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05180.svg), [剩/05269.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05269.svg), [北/05317.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05317.svg), [嚥/056a5.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/056a5.svg), [埀/057c0.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/057c0.svg), [燕/071d5.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/071d5.svg), [背/080cc.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/080cc.svg), [臙/081d9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/081d9.svg), [讌/08b8c.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08b8c.svg), [驥/09a65.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09a65.svg)

**Comment by wareya** [comment]
The left component in 北 is not a variant of 爿, but rather it's a mirrored variant of one of the components that merged into the modern 匕*. Early forms of 北 were symmetrical, even in oracle bone script. You can see the distinction in real 教科書 typefaces and handwriting fonts, where the left component of 北 has the bottom horizontal line pass by the vertical line, rather than the other way around.
