### ISSUE TITLE
犭 character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#135]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by scriptin** [comment]
This one is already marked as a separate component in all kanji below. It's just a glyph itself that is missing.

[潴/06f74.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/06f74.svg), [犯/072af.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072af.svg), [犲/072b2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072b2.svg), [犹/072b9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072b9.svg), [狂/072c2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072c2.svg), [狃/072c3.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072c3.svg), [狄/072c4.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072c4.svg), [狆/072c6.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072c6.svg), [狎/072ce.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072ce.svg), [狐/072d0.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072d0.svg), [狒/072d2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072d2.svg), [狗/072d7.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072d7.svg), [狙/072d9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072d9.svg), [狛/072db.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072db.svg), [狠/072e0.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072e0.svg), [狡/072e1.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072e1.svg), [狢/072e2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072e2.svg), [狩/072e9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072e9.svg), [独/072ec.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072ec.svg), [狭/072ed.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072ed.svg), [狷/072f7.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072f7.svg), [狸/072f8.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072f8.svg), [狹/072f9.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072f9.svg), [狼/072fc.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072fc.svg), [狽/072fd.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/072fd.svg), [猊/0730a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0730a.svg), [猖/07316.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07316.svg), [猗/07317.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07317.svg), [猛/0731b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0731b.svg), [猜/0731c.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0731c.svg), [猝/0731d.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0731d.svg), [猟/0731f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0731f.svg), [猥/07325.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07325.svg), [猩/07329.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07329.svg), [猪/0732a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0732a.svg), [猫/0732b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0732b.svg), [猯/0732f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0732f.svg), [猴/07334.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07334.svg), [猶/07336.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07336.svg), [猾/0733e.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0733e.svg), [猿/0733f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0733f.svg), [獄/07344.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07344.svg), [獅/07345.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07345.svg), [獏/0734f.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0734f.svg), [獗/07357.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07357.svg), [獨/07368.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07368.svg), [獪/0736a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0736a.svg), [獰/07370.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07370.svg), [獲/07372.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07372.svg), [獵/07375.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/07375.svg), [獺/0737a.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0737a.svg), [荻/0837b.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0837b.svg), [蕕/08555.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08555.svg), [誑/08a91.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08a91.svg), [逖/09016.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09016.svg)
