### ISSUE TITLE
⻖ character request

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#136]
https://en.wikipedia.org/wiki/Simplified_table_of_Japanese_kanji_radicals

**Comment by scriptin** [comment]
Both "town" (right) and "mound" (left) already exist: [⻏/02ecf.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/02ecf.svg), [⻖/02ed6.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/02ed6.svg)

**Comment by benkasminbullock** [comment]
This seems to already exist, so let's close this.
