### ISSUE TITLE
Some stroke numbers are too far away from starting points of their corresponding strokes

### ISSUE THREAD

**Issue by scriptin** [KanjiVG/kanjivg#143]
Some numbers are too far from starting positions of their corresponding nodes. Record is set by [臓/081d3.svg](http://kanjivg.tagaini.net/viewer.html?kanji=%E8%87%93): stroke 10 is located closer to an end of its' stroke than to the starting point, the distance is close to 35. This may be very misleading when viewing the image without inspecting the code. I think that 20-25 is a good limit, but this is rather subjective. Keeping this number small would allow to detect when numbers don't match strokes, or just misplaced.

Gist: https://gist.github.com/scriptin/303e4b565cd4acbc835381fe811edd15

**Comment by scriptin** [comment]
Edited the issue because my understanding of SVG path data was incomplete: relative `move-to` in a starting position is still interpreted as absolute coordinates.

> If a relative moveto (m) appears as the first element of the path, then it is treated as a pair of absolute coordinates. In this case, subsequent pairs of coordinates are treated as relative even though the initial moveto is interpreted as an absolute moveto.
- https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands

**Comment by ospalh** [comment]
First, to get a better overview:
You list these characters: 「彙菓椀菓編森彙贓Ｍ臓鬢藁𠂤翡騙暮臓贓楙臓諞麝翩翡嚇翩蝙髦M騙槊東森躍蘖騙鬢儁贓藜臓髦象藜諞暮麝蘖椀槊楙婉騙鬢薙贓矜推場鑿蝙婉碗碗務」(Btw, why didn’t you print M and Ｍ in that list?)
and these files:
"""
05f59.svg
083d3.svg
06900-Kaisho.svg
083d3-Kaisho.svg
07de8.svg
068ee.svg
05f59-Kaisho.svg
08d13-KaishoHzFstTenFst.svg
0ff2d.svg
081d3.svg
09b22-Kaisho.svg
085c1.svg
200a4.svg
07fe1-MdFst.svg
09a19-Hyougai.svg
066ae.svg
081d3-KaishoHzFstTenFst.svg
08d13-Kaisho.svg
06959.svg
081d3-Kaisho.svg
08ade.svg
09e9d-Kaisho.svg
07fe9.svg
07fe1.svg
05687.svg
07fe9-Kaisho.svg
08759-Kaisho.svg
09ae6.svg
0004d.svg
09a19-HyougaiKaisho.svg
069ca.svg
06771-Kaisho.svg
068ee-Kaisho.svg
08e8d.svg
08616-Kaisho.svg
09a19.svg
09b22.svg
05101.svg
08d13.svg
085dc.svg
081d3-KaishoHzFst.svg
09ae6-HzFst.svg
08c61.svg
085dc-Kaisho.svg
08ade-Kaisho.svg
066ae-Kaisho.svg
09e9d.svg
08616.svg
06900.svg
069ca-Kaisho.svg
06959-Kaisho.svg
05a49-Kaisho.svg
09a19-HyougaiKaishoVt6.svg
09b22-KaishoHzFst.svg
08599.svg
08d13-KaishoHzFst.svg
077dc.svg
063a8.svg
05834-Kaisho.svg
0947f.svg
08759.svg
05a49.svg
07897-Kaisho.svg
07897.svg
052d9.svg
"""

**Comment by ospalh** [comment]
>This may be very misleading when viewing the image without inspecting the code

I think you have it backwards. A measure like yours is a way to find *candidates* to look at. But than you have to use the images to look for a better place to put the number. And quite often i don’t see one. 

Take 彙 as an example. If you count through your list, you see `25.097021735656202` as the twelfth item. (And good thing we know the distance is 25.097021735656202 and not 25.097021735652602. I think listing only the problem stroke number and the distance with one decimal would have been better. Along the lines of “Stroke 12: Distance 25.1 too large”.) Looking at the SVG, sure enough, the number 12 is a bit away from the start of the stroke. But then it is clear a) which stroke should be the 12th and b) that the number was placed there because there isn’t that much room closer to the stroke start. 

When you actually look through the list, there are some where the numbers could be moved a bit, but quite often there isn’t much room to move the number closer.

**Comment by scriptin** [comment]
Thank you for looking into that, and sorry for the messy output. I didn't have enough time to polish it.

---

Of course, I looked through images themselves, and I totally agree that in some cases it's just a way it has to be, because there's not enough room.

Indeed, this method is only for searching *potential* problems, because there's no actual shape/composition analysis being performed. I'm not sure if it's even possible to fully automate such validation rules properly, but I believe that imprecise tests which may produce false alarms are still much better than unnoticed problems caused by lack of testing.

Notice that these all messages have severity of "warning", so they are not considered bugs. This is an example of exploratory testing, so don't expect it to be objective in all cases. I'm just testing away like a maniac.

---

For one specific kanji I mentioned ([臓/081d3.svg](http://kanjivg.tagaini.net/viewer.html?kanji=%E8%87%93)) I see a way of making it better by placing "10" where "11" is, moving the latter to the right a bit.

But I'm not saying it *has* to be fixed, because I'm not 100% sure that it should be considered a problem at all. I created this issue to ask for your opinion, because I though that people may not have though such problem could exist.

---

As for checker output:

> Btw, why didn’t you print M and Ｍ in that list?

Symbols are taken from XML contents, from the attribute of a root group. If this attribute is missing, "NA" is printed. I'll fix that.

> I think listing only the problem stroke number and the distance with one decimal would have been better. Along the lines of “Stroke 12: Distance 25.1 too large”.

Yes, I'll implement that.

---

What do you think we should do? I see few possible resolutions:

1. Ignore these warnings, leave just for extra caution
2. Set a threshold to a higher number, e.g. 42. That way we will only see if something is way off
3. Fix what's possible (if anything), ignore the rest
4. Invent a better algorithm?
5. Fix the problem in a more radical way, e.g. use smaller font sizes for "tight" cases

**Comment by ospalh** [comment]
The algorithm wasn’t really the problem. As i said, that’s good to show you candidates where you maybe should move the numbers.

I just didn’t like posting the raw output like that all that much, at least not as an issue. Maybe as a gist. I would have preferred it if here you would have posted the results of sifting through the list by hand. 
Ideally sorted into categories, like “Please fix” for characters like 𠂤, where the numbers are off for no reason at all, and “Maybe fix” for some and “the numbers are off, but i don’t know where to put them either” for the rest. Just my opinion.

>Symbols are taken from XML contents

Hmm. Looks like you found another problem. I see no reason why the ASCII characters, and their full width relatives, shouldn’t have the `kvg:element="NN"` set. Maybe i will look into adding them. Some day. (And i guess for the full width Ｍ etc. you could use `original="M"`.)

**Comment by scriptin** [comment]
Got it. Created a gist with more readable messages.

**Comment by scriptin** [comment]
> Hmm. Looks like you found another problem. I see no reason why the ASCII characters, and their full width relatives, shouldn’t have the kvg:element="NN" set.

This can be automated. If you think it's a right thing to do, I can add such feature into my project.

**Comment by benkasminbullock** [comment]
The stroke numbers on 081d3 seem not too far away from the strokes at the moment:
![081d3](https://user-images.githubusercontent.com/102005/163057820-b9a7accd-643a-4362-9c15-a2dadf0bf3ac.png)
I don't see an action to be taken in this issue, it seems more like a discussion, and it was six years ago now, so I'll close this. Please do reopen if you're not satisfied.
