### ISSUE TITLE
katakana character ヨ is written as the pig snout radical 彐

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#144]

**Comment by scriptin** [comment]
They look pretty different to me: [ヨ/030e8.svg](http://kanjivg.tagaini.net/viewer.html?kanji=ヨ) vs [彐/05f50.svg](http://kanjivg.tagaini.net/viewer.html?kanji=彐). Maybe, you mean they *should* be the same?

**Comment by wareya** [comment]
Maybe 彐 needs to look different? Every display font I've checked has the middle stroke not pass the vertical line, and has the bottom line pass the vertical line, like this: http://i.imgur.com/M5NTRVu.png

**Comment by benkasminbullock** [comment]
I think this issue should be closed since no clarification was provided of what the issue was. Please reopen if not satisfied.
