### ISSUE TITLE
膨 = 士 not 土?

### ISSUE THREAD

**Issue by gomihog** [KanjiVG/kanjivg#145]
I believe the character for 膨 may be ever so slightly incorrect as it appears in the viewer. Looking over many similar characters it seems to me that the top middle portion of the character should look more like 士 than 土. The font used by the Japan Kanji Aptitude Testing Public Interest Foundation shows it looking like 士. You can view the Japan Kanji Aptitude Testing Public Interest Foundation's  list of characters which contains 膨 at the following address. (See page 11, second row from the bottom, fourth column from the left.)

Kanji Aptitude Test List
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwii7a3rs6POAhUKwWMKHQKEAAUQFggeMAA&url=http%3A%2F%2Fwww.kanken.or.jp%2Fkanken%2Foutline%2Fdata%2Foutline_degree_national_list.pdf&usg=AFQjCNHaycQnDc_1rYIjX0mJgQXKNhDzfg&sig2=f0B01h3Cp6jZ6x4odkkBig

Furthermore, the font used on the official MEXT (Ministry of Education, Culture, Sports, Science and Technology) website also appears to look like 士

MEXT List (Cache):
http://webcache.googleusercontent.com/search?q=cache:uLxPzQI8YK0J:www.mext.go.jp/b_menu/hakusho/nc/k19811001001/k19811001001.html+&cd=1&hl=ja&ct=clnk&gl=us

A quick Google search will also show many websites showing the portion of the character in question here as 士 instead of 土.

Thank you for your consideration on changing the font.

**Comment by wareya** [comment]
In practice, kyoukashotai fonts generally make the two horizontal bars nearly equal-length in 膨 for some reason, even though they don't do it with other characters that have the same component. http://i.imgur.com/Aeoj1ZC.png

**Comment by ospalh** [comment]
@gomihog: 

Which viewer are you talking about? Maybe that program uses outdated data.
Anyway, this has been fixed a while ago, as you said from 土 to 士: 4e812945ac8280f77115362d2de286c3dd0006f0, see the current version [here](https://github.com/KanjiVG/kanjivg/blob/master/kanji/081a8.svg), try the “document” “display the rich diff” icon to get a visual comparison.

**Comment by wareya** [comment]
They're talking about the outdated demo site: http://kanjivg.tagaini.net/viewer.html?kanji=膨
