### ISSUE TITLE
躓 strokes 11 and 15 drawn backwards

### ISSUE THREAD

**Issue by IllDepence** [KanjiVG/kanjivg#146]
Both last strokes (the vertical one) of the 斤 parts are drawn bottom up instead of top down.
For 質 alone it correctly draws them top down.

**Comment by ospalh** [comment]
This was fixed a while ago, see 43aa218, or this image: the red dots mark the starts of strokes:
![default](https://cloud.githubusercontent.com/assets/1690429/18748458/942cabd0-80d2-11e6-8736-882d8b1718ad.png)

As you are talking about the strokes been drawn, i guess you saw it animated in some project. Maybe their data is out of data, and you can tell them to download and use a newer [version](https://github.com/KanjiVG/kanjivg/releases/tag/r20160426).
