### ISSUE TITLE
琥 #7 and #8 should be swapped.

### ISSUE THREAD

**Issue by sollniss** [KanjiVG/kanjivg#147]
Somehow [jisho](http://jisho.org/search/%E7%90%A5%20%23kanji) (which uses kanjivg) has it correctly.

What happened?

**Comment by ospalh** [comment]
You have old data happened?
The viewer of this project, http://kanjivg.tagaini.net/viewer.html, has old data happened? (See #148, this wouldn’t be the first time that’s a problem.)

Where exactly did you see the version you didn’t like?
And, especially when there are, or seem to be, more then one version of a kanji floating around, it is helpful to describe which way you saw it, and where, and which way (you think) it should be.

For example, “For 琥, strokes 7, 8 should be vertical, horizontal, not horizontal, then vertical as it is in this and that place.”

For 琥, the standard variant was changed from 7, 8 horizontal, vertical to vertical, horizontal a while ago, 42f9f89a3bafd, now it looks like this:

![default](https://cloud.githubusercontent.com/assets/1690429/18870606/b1b92042-84b1-11e6-9abd-72fc1192f1f6.png)

(But looking at the diff, the internal stroke types may be wrong now)

**Comment by sollniss** [comment]
I had old data and confirmed it with the viewer which also had old data. The new data has the correct version.

I apologise.
