### ISSUE TITLE
備 given in wrong variant

### ISSUE THREAD

**Issue by rathsky** [KanjiVG/kanjivg#157]
The Jōyō kanji 備 is rendered in the traditional variant that's wrong/uncommon for Japan: 
![05099](https://cloud.githubusercontent.com/assets/887320/25539632/57bcfc96-2c48-11e7-92f0-cf6a5aa6c079.png)

How it ought to be: eg. [GlyphWiki](http://glyphwiki.org/wiki/u5099), [Wiktionary](https://en.wiktionary.org/wiki/%E5%82%99), a font like the Japanese style of Google's Noto, or [this image](https://ja.wikipedia.org/wiki/%E5%82%99#/media/File:%E8%BB%8D%E5%9B%A3.JPG) (see bottom right) from the Japanese Wiki page.

**Comment by ospalh** [comment]
Thanks for reporting this.

**Comment by rathsky** [comment]
I think there ought to be some empty space so the 卄 and 厂 don't actually touch.

**Comment by ospalh** [comment]
I thought about that a bit.
Most fonts i checked had stroke 6 touch strokes 4,5.
![05099_a](https://cloud.githubusercontent.com/assets/1690429/25635711/664d0d16-2f7f-11e7-90e0-3266b2a0be7d.png)

Admittedly a list from JIS i have lying around does have the gap you suggested, but “lots of people (fonts) do it this (touching) way” is good enough for me. I guess if you do want this you will have to do it yourself.

**Comment by wareya** [comment]
The IPA fonts (the jis-2004 version if there's two versions) have basically the canonical glyph forms for the joyo kanji. In that, the 卄 and 厂 touch. They also touch in (the jis-2004 versions of) Yu Kyokasho and FC Kyouka, which are handwriting-style print fonts.

**Comment by ospalh** [comment]
So, fixed via #158.
