### ISSUE TITLE
Wrong strokes for 捗

### ISSUE THREAD

**Issue by Rychu** [KanjiVG/kanjivg#159]
捗 kanji has simplified 少 part. In kanji vg 少, while the correct writing doesn't have the rightmost short stroke. This is stroke 10 in kanjivg.

http://kakijun.jp/page/choku11200.html

**Comment by ospalh** [comment]
Thanks for reporting this, but i [fixed](https://github.com/KanjiVG/kanjivg/commit/7f8f4be0fc1e6257f30c2a2533a4be310c9c7cd1?short_path=cd64911#diff-cd6491112ba2992a0d7756cf7a9fc5ee) this a while ago, you are probably using outdated data. Where did you see this exactly?
If it was the web viewer, we know they are outdated, #148.
If it was somewhere else, could you please tell whoever is responsible that they should update their kanjivg data?

**Comment by Rychu** [comment]
Well, yes, I've checked in the browser.
I've rechecked in the kanji bundle, and actually the base svg is correct (the stroke is in the versions with suffixes, but I guess this is intentional).
Sorry, for causing commotion. Since there actually isn't problem, I'll close the ticket.

**Comment by Gnurou** [comment]
We are the ones who should apologize for the fact the data in the web viewer is outdated. I have been working my web skills a bit lately, so hopefully we can remedy this sometime soon.
