### ISSUE TITLE
Errors in 乘 and 尨

### ISSUE THREAD

**Issue by vitaliylag** [KanjiVG/kanjivg#161]
Kanji 乘 have this code:

```xml
<g id="kvg:04e58" kvg:element="乘">
	<g id="kvg:04e58-g1" kvg:element="禾" kvg:part="1">
		<g id="kvg:04e58-g2" kvg:element="丿" kvg:radical="general">
			<path id="kvg:04e58-s1" kvg:type="㇒" d="M68.51,10.5c-0.26,1.25-0.19,1.44-0.74,1.87C62.5,16.5,46.25,22.5,25.75,25"/>
		</g>
	</g>
	<g id="kvg:04e58-g3" kvg:element="木" kvg:part="1">
		<path id="kvg:04e58-s2" kvg:type="㇐" d="M15.25,33.69c0.78,0.33,3.9,1.2,5.96,0.98c9.33-0.98,49.51-5.65,65.33-6.55c2.07-0.12,4.67,0.39,5.96,0.72"/>
	</g>
	<g id="kvg:04e58-g4" kvg:element="北">
		<g id="kvg:04e58-g5" kvg:position="left">
			<path id="kvg:04e58-s3" kvg:type="㇐" d="M15.5,52.03c1.39,0.29,1.74,0.44,3.14,0.44s15.18-2.36,16.4-2.36"/>
			<path id="kvg:04e58-s4" kvg:type="㇑" d="M34.19,39.44c1.05,0.89,1.42,2.92,1.42,3.51s0.17,17.37,0.17,18.99"/>
			<path id="kvg:04e58-s5" kvg:type="㇀" d="M16.26,67.62c2.16,1.24,3.82,1.31,5.41,0.69c9.55-3.73,12.61-4.83,17.66-6.91"/>
		</g>
		<g id="kvg:04e58-g6" kvg:element="匕" kvg:position="right">
			<path id="kvg:04e58-s6" kvg:type="㇒" d="M87.32,37.58c0.13,0.22,0.19,0.82-0.13,1.18c-3.06,3.46-10.59,8.52-17.2,10.33"/>
			<path id="kvg:04e58-s7" kvg:type="㇟" d="M66.22,36c0.52,0.4,1.21,1.19,1.21,2c0,0.55,0.17,18.06,0.17,19.71c0,4.23,2.91,5.34,12.16,5.34c8.25,0,11.99-1.04,11.99-5.45"/>
		</g>
	</g>
	<g id="kvg:04e58-g7" kvg:element="禾" kvg:part="2">
		<g id="kvg:04e58-g8" kvg:element="木" kvg:part="1">
			<path id="kvg:04e58-s8" kvg:type="㇑" d="M52.72,22.5c0.89,0.49,1.42,2.19,1.6,3.16c0.18,0.97,0,68.26-0.18,74.34"/>
			<path id="kvg:04e58-s9" kvg:type="㇒" d="M54,56.18C47.46,70.47,30.75,86.25,15.75,94.5"/>
			<path id="kvg:04e58-s10" kvg:type="㇏" d="M54.25,58.21c7,8.04,26,25.29,33.96,30.99c1.93,1.38,3.44,2.13,5.29,2.55"/>
		</g>
	</g>
</g>
````

But the code should be
```xml
<g id="kvg:04e58" kvg:element="乘">
	<g id="kvg:04e58-g1" kvg:element="禾" kvg:part="1">
		<g id="kvg:04e58-g2" kvg:element="丿" kvg:radical="general">
			<path id="kvg:04e58-s1" kvg:type="㇒" d="M68.51,10.5c-0.26,1.25-0.19,1.44-0.74,1.87C62.5,16.5,46.25,22.5,25.75,25"/>
		</g>
		<g id="kvg:04e58-g3" kvg:element="木" kvg:part="1">
			<path id="kvg:04e58-s2" kvg:type="㇐" d="M15.25,33.69c0.78,0.33,3.9,1.2,5.96,0.98c9.33-0.98,49.51-5.65,65.33-6.55c2.07-0.12,4.67,0.39,5.96,0.72"/>
		</g>
	</g>
	<g id="kvg:04e58-g4" kvg:element="北">
		<g id="kvg:04e58-g5" kvg:position="left">
			<path id="kvg:04e58-s3" kvg:type="㇐" d="M15.5,52.03c1.39,0.29,1.74,0.44,3.14,0.44s15.18-2.36,16.4-2.36"/>
			<path id="kvg:04e58-s4" kvg:type="㇑" d="M34.19,39.44c1.05,0.89,1.42,2.92,1.42,3.51s0.17,17.37,0.17,18.99"/>
			<path id="kvg:04e58-s5" kvg:type="㇀" d="M16.26,67.62c2.16,1.24,3.82,1.31,5.41,0.69c9.55-3.73,12.61-4.83,17.66-6.91"/>
		</g>
		<g id="kvg:04e58-g6" kvg:element="匕" kvg:position="right">
			<path id="kvg:04e58-s6" kvg:type="㇒" d="M87.32,37.58c0.13,0.22,0.19,0.82-0.13,1.18c-3.06,3.46-10.59,8.52-17.2,10.33"/>
			<path id="kvg:04e58-s7" kvg:type="㇟" d="M66.22,36c0.52,0.4,1.21,1.19,1.21,2c0,0.55,0.17,18.06,0.17,19.71c0,4.23,2.91,5.34,12.16,5.34c8.25,0,11.99-1.04,11.99-5.45"/>
		</g>
	</g>
	<g id="kvg:04e58-g7" kvg:element="禾" kvg:part="2">
		<g id="kvg:04e58-g8" kvg:element="木" kvg:part="2">
			<path id="kvg:04e58-s8" kvg:type="㇑" d="M52.72,22.5c0.89,0.49,1.42,2.19,1.6,3.16c0.18,0.97,0,68.26-0.18,74.34"/>
			<path id="kvg:04e58-s9" kvg:type="㇒" d="M54,56.18C47.46,70.47,30.75,86.25,15.75,94.5"/>
			<path id="kvg:04e58-s10" kvg:type="㇏" d="M54.25,58.21c7,8.04,26,25.29,33.96,30.99c1.93,1.38,3.44,2.13,5.29,2.55"/>
		</g>
	</g>
</g>
```
First "木" is in different group and second "木" should have kvg:part="2".

<br><br>
Next, 尨 kanji:
"丶" group should have kvg:part="1" instead of "2".

<br><br>
Also there is 40 kanji does not have kvg:number attribute for its groups but must have:
亭帯欄脩兢哥彁戔棗棘棧歌殘淺濺牋盞竸箋綫蕀謌賤踐錢餞壌壤嬢孃攘曩禳穣穰譲讓醸釀驤

First 4 of it are kanji without repeating elements, next 22 with repeating elements and last 14 with 三. Here is table which elements dont have kvg:number attribute:
亭:   高   (4ead)
帯:   川   (5e2f)
欄:   日   (6b04)
脩:   攸   (8129)
兢:   兄兄  (5162)
哥:   丁丁  (54e5)
彁:   丁丁  (5f41)
戔:   弋弋  (6214)
棗:   木木  (68d7)
棘:   木木  (68d8)
棧:   弋弋  (68e7)
歌:   丁丁  (6b4c)
殘:   弋弋  (6b98)
淺:   弋弋  (6dfa)
濺:   弋弋  (6ffa)
牋:   弋弋  (724b)
盞:   弋弋  (76de)
竸:   音音  (7af8)
箋:   弋弋  (7b8b)
綫:   弋弋  (7dab)
蕀:   木木  (8540)
謌:   丁丁  (8b0c)
賤:   弋弋  (8ce4)
踐:   弋弋  (8e10)
錢:   弋弋  (9322)
餞:   弋弋  (991e)
壌:   三   (58cc)
壤:   三   (58e4)
嬢:   三   (5b22)
孃:   三   (5b43)
攘:   三   (6518)
曩:   三   (66e9)
禳:   三   (79b3)
穣:   三   (7a63)
穰:   三   (7a70)
譲:   三   (8b72)
讓:   三   (8b93)
醸:   三   (91b8)
釀:   三   (91c0)
驤:   三   (9a64)

**Comment by ospalh** [comment]
Hi, Welcome (or did i miss an earlier contribution?) and thanks for your contribution.

Looks like you basically did the work for the first one.
Could you perhaps do a pull request, or at least push the change to github?

In general, the part and number metadata are a bit out out of date or incorrect, yes.
But i don’t think anybody (else) is motivated to do much about this. At least i am not. I use the kanji visually, not the metadata like the groups. If this is important to you, the best way would be to do this yourself.

Sorry to not be more helpful.

**Comment by vitaliylag** [comment]
For contribute do I just need to change svg files and make pull request?

**Comment by vitaliylag** [comment]
If I also change 乙 to 乚 and 𠂊 to ⺈ in needed kanji, will it be OK?

**Comment by vitaliylag** [comment]
I guest yes, I just need to change needed svg files. Can I also add the instruction how to contribute from here https://github.com/KanjiVG/kanjivg to README.txt?

I think some people may think if they just change svg files then some scripts can override the changes. When I open the project first time I don't know how it was created :) I cannot read python scripts too :)

**Comment by ospalh** [comment]
> For contribute do I just need to change svg files and create pull request?

Pretty much, yes.

>… change 乙 to 乚,  𠂊 to ⺈…

Hmm. If that is what the element is, then yes.
Otoh, there are the `kvg:variant` and `kvg:original` attributes.
Check out kanji with e.g.  「亻」 at the left, things like  「仏」 (04ecf.svg). There you have `<g id="kvg:04ecf-g1" kvg:element="亻" kvg:variant="true" kvg:original="人" kvg:position="left" kvg:radical="general">`

> … 竹 to ⺮

Odd. I don’t know why ⺮ in the from of  `kvg:element="⺮" kvg:variant="true" kvg:original="竹"` doesnt appear in the data (the SVG files). I think that would be OK to change.

> … I just don't know Japanese well,

Neither do i. So for things that are not obvious (like flipped numbers), i’d appreciate some third opinion.

**Comment by vitaliylag** [comment]
I created PL, can you see it?

**Comment by vitaliylag** [comment]
I have created PR, can you see it?

**Comment by Gnurou** [comment]
Are you referring about this one?

https://github.com/KanjiVG/kanjivg/pull/164

If so, then yes. :) It always take a while before we find time to process them though, sorry about that.

**Comment by vitaliylag** [comment]
OK, thanks. I just wanted response you will see it when you have a time.

**Comment by weirdalsuperfan** [comment]
Any reason this hasn't been merged?

**Comment by benkasminbullock** [comment]
> Any reason this hasn't been merged?

@vitaliylag added more and more commits to the pull request, making it very hard to work out what had been changed, so it will take some time to either merge this or disentangle the commit which fixes it from the other commits.

**Comment by benkasminbullock** [comment]
The pull request was done some time ago but on a different branch. After five years, I doubt if anyone is going to go back over all of this to try to see if anything was lost, so let's close it.
