### ISSUE TITLE
Errors in きさぎざ

### ISSUE THREAD

**Issue by vitaliylag** [KanjiVG/kanjivg#163]
き contains 3 stokes not 4.
さ contains 2 stokes not 3.
ぎ contains 5 stokes not 6.
ざ contains 4 stokes not 5.

Or am I wrong?

**Comment by ospalh** [comment]
You are welcome to add the 3/2 stroke (5/4 stroke good thing there are no まる/半濁点 versions) style kana as variants. But when you actually count the strokes in the svgs, you get 3 or 4 for the plain (not-tenten) kana.
Dto. the one vs. two stroke variants of そ.
Hand writing guides i have checked have き with 4, さ with 3 and そ with 1.

https://github.com/KanjiVG/kanjivg/blob/master/kanji/0304d.svg
https://github.com/KanjiVG/kanjivg/blob/master/kanji/03055.svg
https://github.com/KanjiVG/kanjivg/blob/master/kanji/0305d.svg

**Comment by vitaliylag** [comment]
Actually I forgot to see how it really looks and thought you don't use hand writing styles.
