### ISSUE TITLE
釜 Stroke 4 Missing

### ISSUE THREAD

**Issue by lxmmxl56** [KanjiVG/kanjivg#165]
I guess this might be a style choice but I couldn’t seem to find any other examples of writing the kanji without the right sweeping stroke.

**Comment by ospalh** [comment]
I’m not quite sure what you are talking about.
Do you have a picture and a source where a stroke was missing? Which one exactly? (Even if one stroke is missing, one is bound to be labeled 4.)

* Here is the kanji in the raw data: https://github.com/KanjiVG/kanjivg/blob/master/kanji/091dc.svg
* Or when you type 釜 into the online viewer: http://kanjivg.tagaini.net/viewer.html
* Here a picture of a colorized version together with the character in some other fonts  ![kessel](https://user-images.githubusercontent.com/1690429/31859469-c1f7fcf6-b70c-11e7-9f8a-322e8db2bf83.png)

All have as stroke 4 the NW→SE diagonal ㇏ stroke of the top 父 element.
What did you see, and what did you expect?

**Comment by benkasminbullock** [comment]
No clarification has been provided and I confirm with @ospalh that I cannot see a problem at all when comparing this to various other sources of information. Please open the issue again if you are not satisfied.
