### ISSUE TITLE
松: right part of ハ seems like a rotated ~

### ISSUE THREAD

**Issue by twwn** [KanjiVG/kanjivg#166]
If you look at the character style of 松 in the [常用漢字表](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/pdf/joyokanjihyo_20101130.pdf), you'll notice that its ハ is meant to look like its parts are curved toward a bottom middle.

Instead, at the moment the right part looks more like a ~ rotated by 45ˇ to the right.

**Comment by ospalh** [comment]
When you look at it at [Kakijun](https://kakijun.jp/page/08152200.html), it has a hint of this wave in it, including the  教科書体 (Kyōkasho-tai, textbook type) that we mostly aim for.
I guess it’s a bit strong in the SVG version here. Maybe i’ll straighten it out a bit.

**Comment by benkasminbullock** [comment]
There are two files for this character, kanji/0677e-Kaisho.svg and kanji/0677e.svg. The only difference I can see is that stroke 4 and stroke 6 look different in the "Kaisho" variant, so perhaps it's mislabelled.

https://github.com/KanjiVG/kanjivg/blob/master/kanji/0677e.svg

https://github.com/KanjiVG/kanjivg/blob/master/kanji/0677e-Kaisho.svg
