### ISSUE TITLE
備: number 12 obstructed by its stroke

### ISSUE THREAD

**Issue by nwwt** [KanjiVG/kanjivg#167]
As [one can see](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05099.svg), the "1" is "12" overlaps with its stroke.

Normally only a minor inconvenience, but users like the Anki plugin use the same color for number and strokes, rendering the "1" mostly invisible.

**Comment by benkasminbullock** [comment]
Thank you for the bug report. This is fixed by commit 1f73d9b891a401cbf54316dfab365e82cfec0854.

The error persists in 05099-Kaisho.svg and two other files have different positions for the 12.
