### ISSUE TITLE
Top right strokes of 溢 slightly off

### ISSUE THREAD

**Issue by nwwt** [KanjiVG/kanjivg#169]
The basic shape matches JIX X 0213:2004, but if you look [closely on the table](https://ja.wikipedia.org/wiki/JIS_X_0213#/media/File:JIS_X_0213_2000-2004.gif) (top row, 4th from left):

1. the four diagonal strokes look like they ought to be further at the side (so as to barely make it past vertically over the "border" given by 皿)

2. in particular, the horizontal line should not exceed the close edges of the two bottom strokes (八-like), and unlike currently, where it looks like it's toughing, ever so slightly seem to be hovering above them.

I'm not sure what to make of [GlyphWiki's entry](http://glyphwiki.org/wiki/u6ea2), though.

**Comment by wtn** [comment]
[MJ015692](https://mojikiban.ipa.go.jp/search/detail/MJ015692) is the appropriate reference glyph. GlyphWiki [u6ea2](http://glyphwiki.org/wiki/u6ea2) matches it well.

It can be ambiguous how to adapt a 明朝 typeface for a handwriting style. Here's KanjiVG [06ea2.svg](https://github.com/KanjiVG/kanjivg/blob/1eaef89b17e088f14a13cbb7091607b2ba0530fb/kanji/06ea2.svg), and the attached image shows this shape in Motoya Kyotai Pro (CID+7635). That's probably the ideal form.

<img width="626" alt="motoyakyotaicid7635 png" src="https://user-images.githubusercontent.com/35801/42120113-48eab97c-7bdb-11e8-80c6-0ad59d091df3.png">

**Comment by benkasminbullock** [comment]
I think this issue should be closed, since there is no agreement that KanjiVG is in error and no clarification after four years. Please reopen if not satisfied.
