### ISSUE TITLE
No kvg:element in Top Level Group for Kana Characters?

### ISSUE THREAD

**Issue by raeldor** [KanjiVG/kanjivg#170]
Hi,

It's been a while since I downloaded the XML and it looks like the format has changed.  Previously you had...

`
<kanji midashi="を" id="3092">
<strokegr>
	<stroke type="None" path="M7.75,27.87c1.62,1.13,3.17,1.64,6.01,1.12C24.62,27,30.5,25.62,38.47,24.27c3.64-0.62,5.65-0.93,8.4-0.75"/>
	<stroke type="None" path="M29.12,14.38c0.75,1,1.48,3.22,0.38,5.62c-4.62,10.12-10,20.75-17.12,30.25c-9.25,12.33-9.25,11.19,2.12,2.5c9-6.88,23.75-12.12,22.88,19.88"/>
	<stroke type="None" path="M62.25,39.88c0.62,1.75,0,4-3,5.75S9.63,69.79,14.5,83.88c3.28,9.48,17.93,9.12,29.98,7.75c4.48-0.51,9.15-1.12,12.4-1.75"/>
</strokegr>
`

Now you have...

`
<kanji id="kvg:kanji_03092">
<g id="kvg:03092">
	<path id="kvg:03092-s1" d="M28.56,27.87c1.62,1.13,3.17,1.64,6.01,1.12c10.86-1.99,16.74-3.37,24.71-4.72c3.64-0.62,5.65-0.93,8.4-0.75"/>
	<path id="kvg:03092-s2" d="M49.93,14.38c0.75,1,1.48,3.22,0.38,5.62c-4.62,10.12-10,20.75-17.12,30.25c-9.25,12.33-9.25,11.19,2.12,2.5c9-6.88,23.75-12.12,22.88,19.88"/>
	<path id="kvg:03092-s3" d="M83.06,39.88c0.62,1.75,0,4-3,5.75c-3,1.75-49.62,24.16-44.75,38.25c3.28,9.48,17.93,9.12,29.98,7.75c4.48-0.51,9.15-1.12,12.4-1.75"/>
</g>
`

The top level group for kana doesn't have the kvg:element like it does for kanji...

`
<kanji id="kvg:kanji_05b0b">
<g id="kvg:05b0b" kvg:element="嬋">
`

How do I know which kana character it represents without this?

Thanks
Ray

**Comment by BlueRaja** [comment]
I guess you need to use the unicode values
https://en.wikipedia.org/wiki/Hiragana_(Unicode_block)
Not sure why they'd make that change :\

**Comment by benkasminbullock** [comment]
This seems to be resolved by using the Unicode values. Please reopen if not satisfied.

**Comment by benkasminbullock** [comment]
As of https://github.com/KanjiVG/kanjivg/pull/356, the hiragana/katakana now have a kvg:element on the outermost StrokePaths group.
