### ISSUE TITLE
Wrong strokes for 騙

### ISSUE THREAD

**Issue by dmitri-blinov** [KanjiVG/kanjivg#172]

**Comment by dmitri-blinov** [comment]
Somehow imiwa? displays incorrect strokes for 騙, they say they use KanjiVG for data

**Comment by wtn** [comment]
I don't have imiwa, but the current [09a19.svg](https://github.com/KanjiVG/kanjivg/blob/1eaef89b17e088f14a13cbb7091607b2ba0530fb/kanji/09a19.svg) matches [kakijun](https://kakijun.jp/page/hend19200.html) and animates correctly in Renzo's Japanese app. I think this issue can be closed (unless you have more specific information).

**Comment by dmitri-blinov** [comment]
Yes, I will try to contact with imiwa support about it, thanks
