### ISSUE TITLE
Wrong stroke order for 摯

### ISSUE THREAD

**Issue by parsimonhi** [KanjiVG/kanjivg#178]
In 丸 component of 摯, the vertical stroke should be drawn 1st.

**Comment by ospalh** [comment]
You mean like this:

![default](https://user-images.githubusercontent.com/1690429/50056414-29b72c00-015c-11e9-867b-b2ad3086daae.png)

This was fixed [in 2013](https://github.com/KanjiVG/kanjivg/commit/2ce34d819c6c92d9ddbbb71ac4bd661d77ebecea#diff-35a435c7d6e49f37024c530d218a2dfd).

Where did you see the old order? Presumably in the online viewer, but somewhere else, too?
The first is a known problem. In the second case, you should tell the person responsible to get a newer version of the KanjiVG data.

**Comment by parsimonhi** [comment]
I saw it at https://kanjivg.tagaini.net/viewer.html. I didn't check the latest version of kanjiVG. Sorry!
