### ISSUE TITLE
README does not describe current state of the repository.

### ISSUE THREAD

**Issue by amanda-mitchell** [KanjiVG/kanjivg#179]
The README describes the repo as being composed of two folders, `XML` and `SVG`, but the actual structure includes only `kanji` and `kanji_mismatch`. It seems that the `XML` folder was removed at some point and `SVG` became `kanji`, and it's not clear to me what--if anything--from the original description is still relevant.

**Comment by biwkf** [comment]
SVG is XML based. You can view the xml contents of each SVG in text editor. I was also confused by this readme though.

**Comment by david-mitchell** [comment]
@biwkf, what I meant to say was that the readme describes two *folders* with the names “xml” and “svg”, but I now realize that I left the word “folder” out of my description. I have now fixed this.

**Comment by benkasminbullock** [comment]
The bulk of that README file should be deleted since it isn't relevant any more.

https://github.com/KanjiVG/kanjivg/pull/196

Incidentally most of the python scripts don't run with Python 3.

**Comment by benkasminbullock** [comment]
This bug is fixed by removing the statements from README, so I'm closing the issue.
