### ISSUE TITLE
冷 part under roof should contain "one" and "seal"

### ISSUE THREAD

**Issue by erikgerrits** [KanjiVG/kanjivg#182]

**Comment by ospalh** [comment]
Not really.
That, the right side,令, is one where the printed and hand written versions differ.
It is one of the examples given in an official [Jouyou Kanji](https://www.slideshare.net/SaefudinAchada/jouyoukanjihyou-h22) text.
![冷right](https://user-images.githubusercontent.com/1690429/55318608-74db1d80-5473-11e9-974d-474aa2843b48.png)

The “print” version is already here, as a variant, for 令, 冷 and a few others, tagged “Insatsu”, for want of a better name: 
https://github.com/KanjiVG/kanjivg/blob/master/kanji/04ee4-Insatsu.svg
https://github.com/KanjiVG/kanjivg/blob/master/kanji/051b7-Insatsu.svg
&c.

**Comment by ospalh** [comment]
…
Even when Suga Yoshihide or his personal calligrapher writes “令” more in the style you want.
![reiwa_32ff](https://user-images.githubusercontent.com/1690429/55319677-b53b9b00-5475-11e9-957b-90724d5d582f.png)

**Comment by Gnurou** [comment]
I loled at that last one :)

Shall this issue be closed?

**Comment by erikgerrits** [comment]
Thanks a lot for the explanation @ospalh :)
