### ISSUE TITLE
How is kvg:type defined?

### ISSUE THREAD

**Issue by AnnanFay** [KanjiVG/kanjivg#183]
Opening a random file I see paths with `kvg:type="㇑"` and others with `kvg:type="㇑a"`

What does the `a` mean? I assume it's a modifier of some type. Are there other modifiers?

The documentation should link to the full list of these stroke types? Maybe it already does and I just missed it. Only thing I can find is the small comment "The shape of the stroke. It can be used to know how the stroke should be rendered."

**Comment by benkasminbullock** [comment]
Ulrich Apel replied on the KanjiVG mailing list about this.

https://groups.google.com/g/kanjivg/c/iA7ofbeYxJw/m/t_mULofiAQAJ

I've added a bit of documentation here:

https://kanjivg.tagaini.net/format.html#type

Sorry but that is the best I can offer here. You could try asking again on the mailing list and Ulrich might reply with more details.

I'll close this issue anyway, but please reopen it if you're not satisfied.
