### ISSUE TITLE
Is there a TTF version?

### ISSUE THREAD

**Issue by weirdalsuperfan** [KanjiVG/kanjivg#184]
Is it possible to to use this as a font (i.e., not just for individual characters)? Is there a TTF version already?

**Comment by Gnurou** [comment]
I think there is one font here:

https://www.nihilist.org.uk/

I am not sure whether this is made from KanjiVG though. This script would allow you to generate a font from the latest data:

https://github.com/wareya/makefont-kanjivg

**Comment by wareya** [comment]
The nihilist font is a hard-fork of an old version with changes present being made manually to the font data.

**Comment by Gnurou** [comment]
Thanks for the precision. I guess the makefont-kanjivg script may be a better alternative to work with up-to-date data then.
