### ISSUE TITLE
𠮟 character request

### ISSUE THREAD

**Issue by kerukuro** [KanjiVG/kanjivg#185]
Joyo-2010 kanji 𠮟 is missing. Only "acceptable variant" 叱 is present, which has a different stroke order.

**Comment by benkasminbullock** [comment]
This character is actually in the repository and was added in 2015:

https://github.com/KanjiVG/kanjivg/blob/master/kanji/20b9f.svg

Perhaps @kerukuro is looking at an old data file?

I'll close this, but please reopen the issue if you are not satisfied.
