### ISSUE TITLE
Possible Documentation of character coverage?

### ISSUE THREAD

**Issue by DonaldTsang** [KanjiVG/kanjivg#187]
Compared to these repos, how many characters are supported in KanjiVG?
- https://github.com/chanind/hanzi-writer
- https://github.com/d33tah/strokes
- https://github.com/parsimonhi/animCJK

The reason I am asking this, is to try and replicate http://blog.otoro.net/2015/12/28/recurrent-net-dreams-up-fake-chinese-characters-in-vector-format-with-tensorflow/ http://blog.otoro.net/2016/01/05/random-radicals/ and http://otoro.net/kanji/ with more data.

**Comment by ospalh** [comment]
This project is concentrating on the [jōyō kanji](https://en.wikipedia.org/wiki/J%C5%8Dy%C5%8D_kanji) and  contains SVGs for 6744 characters. Not all of those are unique kanji, some are rōmaji letters, radicals, variants of kanji at another code point and the like.
I guess the scope could be documented better.

**Comment by DonaldTsang** [comment]
@ospalh I would hope that an offshoot project can be derived for Traditional and Simplified Chinese since that would be useful for a myriad of applications. All the repo I listed are not "purely strokes" as they included thickness.

**Comment by benkasminbullock** [comment]
This project is not concentrating on Joyo kanji, it does JIS level one and two kanji.

**Comment by benkasminbullock** [comment]
I think this issue is resolved now, please reopen if not satisfied.
