### ISSUE TITLE
Groups in 瀕 are broken

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#189]
In the xml for 瀕, starting from the first stroke of 頁, the first stroke of each group is associated with the previous group. So the top stroke of 頁 becomes the 4th stroke of 少, the left stroke of 目 becomes the second stroke of the top part of 頁, etc. What more, the indentation for each stroke seems to match the group it's supposed to be in, which sometimes mismatches the group it actually is in, indicating only the line order of the xml is incorrect.

**Comment by benkasminbullock** [comment]
There is no "fourth stroke of 少" in the SVG:
![memory](https://user-images.githubusercontent.com/102005/115132408-d5c5f600-a03a-11eb-8cd1-1450a301c68c.png)

It appears that the grouping assumes that there is  少 in the image, but actually the upper right stroke doesn't exist, and the thing labelled as the upper right stroke is in fact the lower diagonal stroke.

According to [IDS](https://github.com/cjkvi/cjkvi-ids), this is a difference between Japanese and Chinese versions of the following component kanji:

U+983B	頻	⿰步頁[GTK]	⿰歩頁[J]

IDS claims that the Japanese version (the [J} marked here) has 少 whereas the Chinese, Taiwanese and Korean versions don't have the upper right stroke. So going from the IDS information, another stroke actually needs to be added.

But here:

https://kaku-navi.com/kanji/kanji08726.html

and here:

https://kakijun.jp/page/hin20200.html

we find the stroke is missing. I've reported this at the IDS issue place:

https://github.com/cjkvi/cjkvi-ids/issues/114

**Comment by benkasminbullock** [comment]
This should be fixed by https://github.com/KanjiVG/kanjivg/pull/231. Could any interested parties please check that is OK? I'll assume it's OK to merge this unless I hear from someone. Thanks.

**Comment by SlugFiller** [comment]
In the new version, the parent of kvg:07015-g8 is kvg:07015-g3. It's supposed to be kvg:07015-g2. This is why the diff looks so much bigger than it should be, due to the one extra indent on strokes that should have remained the same.

**Comment by benkasminbullock** [comment]
@SlugFiller Thank you so much for spotting my error! I've tried to set it straight, if you have time to look again please let me know if I've got it right this time. Again, if I don't hear from you I'll assume it's now OK. Thanks again.

**Comment by SlugFiller** [comment]
@benkasminbullock Okay. Now it looks correct.

**Comment by benkasminbullock** [comment]
Thanks, I'll merge this.
