### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by sbmelvin** [KanjiVG/kanjivg#191]

**Comment by WesleyPerkins** [comment]
I've recently accessed this data and am finding it useful in building a 
handwriting recognition system for kanji.
I find it well conceived, I hope I am respecting the author's rights, 
and I welcome any collaboration in this work.

Wesley Perkins
***@***.***


------ Original Message ------
From: "Stephen Melvin" ***@***.***>
To: "KanjiVG/kanjivg" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 4/17/2021 1:02:56 AM
Subject: [KanjiVG/kanjivg] Is this a dead project? (#191)

**Comment by benkasminbullock** [comment]
There are no commits to the repository since 2017, and there is a backlog of 51 issues, so it's clearly not very active.
