### ISSUE TITLE
Most (all?) kanji are off-center

### ISSUE THREAD

**Issue by BlueRaja** [KanjiVG/kanjivg#192]
It seems that (nearly?) all kanji in this project are off-center.

Examples:

![2021-04-16 15_06_41-Window](https://user-images.githubusercontent.com/650323/115089103-71822580-9ec6-11eb-84bb-77d0423f3727.png)

![2021-04-16 15_08_43-Android Emulator - nexus_6_pie_9_0_-_api_28_5554](https://user-images.githubusercontent.com/650323/115089106-734be900-9ec6-11eb-82f5-25a19c7143cb.png)

Notice how there's a lot of whitespace on the top and left sides, but almost none on the right/bottom.

As a simple example, here are the measurements for 三

![2021-04-16 15_15_33-Android Emulator - nexus_6_pie_9_0_-_api_28_5554](https://user-images.githubusercontent.com/650323/115089888-2e28b680-9ec8-11eb-8ca4-497ce1f712e9.png)

```
<g id="kvg:04e09" kvg:element="三">
    <g id="kvg:04e09-g1" kvg:element="一" kvg:position="top" kvg:radical="general">
        <path id="kvg:04e09-s1" kvg:type="㇐" d="M27.5,23.65c3.09,0.73,6.29,0.36,9.4,0.06c10.2-1,27-2.94,38.97-3.57c3.06-0.16,6.09-0.2,9.14,0.23"/>
    </g>
    <g id="kvg:04e09-g2" kvg:position="bottom">
        <g id="kvg:04e09-g3" kvg:element="一" kvg:radical="general">
            <path id="kvg:04e09-s2" kvg:type="㇐" d="M28.75,55.14c3.13,0.76,6.46,0.43,9.64,0.2c10.03-0.72,23.97-2.63,34.73-3.12c2.7-0.12,5.45-0.16,8.13,0.3"/>
        </g>
        <g id="kvg:04e09-g4" kvg:element="一" kvg:radical="general">
            <path id="kvg:04e09-s3" kvg:type="㇐" d="M13,87.83c3.94,1.01,7.72,0.96,11.75,0.72c18.41-1.07,41.27-3.39,61.12-4.07c3.63-0.13,7.2-0.1,10.75,0.78"/>
        </g>
    </g>
</g>
```

It seems the kanji need to be moved up and to the left ~4-5 units in each direction to be centered.

**Comment by bebop-001** [comment]
Unless I'm interpreting this wrong, I'm not seeing the same thing in Inkscape at the pixel level.   I attached screenshots from Inkscape showing the bounding box for the rendefed and stroked characters for 部 (horizontal measurements only) and the image is 109 pix wide.  The left edge for the stroked char is 11 pix and the right is 97 pix.
![composite](https://user-images.githubusercontent.com/3577718/115122422-c0829600-9f6c-11eb-9fa0-c2faef19a7b3.png)

**Comment by bebop-001** [comment]
I'm not seeing the problem in Inkscape unless I'm reading this wrong.   I put a 1-pix grid on the stroked images as displayed in Inkscape and they look ok to me.

![90e8](https://user-images.githubusercontent.com/3577718/115127195-81af0900-9f89-11eb-8482-0bf931c62101.png)
![4e09](https://user-images.githubusercontent.com/3577718/115127196-82e03600-9f89-11eb-9aa3-949ce041b121.png)

**Comment by benkasminbullock** [comment]
I checked with 部 and saw the same image as @bebop-001, I could not reproduce the images of @BlueRaja. 

The images by @BlueRaja don't seem to be renderings of the SVG data, for example the KanjiVG image uses style "stroke-linecap:round" but the given images by @BlueRaja don't. Also, the @BlueRaja images are of size 384 height by 383 width, which is an odd scaling. It seems quite likely that whatever software @BlueRaja used to render the SVGs is faulty. Here is what Google Chrome makes of the SVG:

![kanjivg-90e8-chrome](https://user-images.githubusercontent.com/102005/115129940-b2448080-a025-11eb-8ac2-7eb3a727f905.png)

@BlueRaja's PNG claims to be made by "Greenshot", which is some kind of screen capture software.

**Comment by BlueRaja** [comment]
@benkasminbullock Oh, hrm, good idea.

The issue seems to be that I read (or assumed??) the canvas was 100x100, but according to [KanjiVG Format](https://kanjivg.tagaini.net/format.html)

> The shape of each stroke is described as a SVG path on an area of size 109x109. 

I don't see that data in the xml file so I'm not sure how Inkscape knows

**Comment by bebop-001** [comment]
On 4/17/21 5:29 PM, BlueRaja wrote:
> @benkasminbullock <https://github.com/benkasminbullock> Oh, hrm, good idea.
> 
> The issue seems to be that I read (or assumed??) the canvas was 100x100, 
> but according to KanjiVG Format <https://kanjivg.tagaini.net/format.html>
> 
>     The shape of each stroke is described as a SVG path on an area of
>     size 109x109.
> 
> I don't see that data in the xml file so I'm not sure how Inkscape knows

It's in the width, height and view box.

 From 4e09.svg lines 10, 11, 12

    width="108"
    height="109"
    viewBox="0 0 109 109"

**Comment by bebop-001** [comment]
On 4/17/21 5:37 PM, steve wrote:
> On 4/17/21 5:29 PM, BlueRaja wrote:
>> @benkasminbullock <https://github.com/benkasminbullock> Oh, hrm, good 
>> idea.
>>
>> The issue seems to be that I read (or assumed??) the canvas was 
>> 100x100, but according to KanjiVG Format 
>> <https://kanjivg.tagaini.net/format.html>
>>
>>     The shape of each stroke is described as a SVG path on an area of
>>     size 109x109.
>>
>> I don't see that data in the xml file so I'm not sure how Inkscape knows
>
> It's in the width, height and view box.
>
> From 4e09.svg lines 10, 11, 12
>
>    width="108"
>    height="109"
>    viewBox="0 0 109 109"
>
Ah... I see ... I don't use the XML file and just assumed SVG. Sorry.

I can't find any view box info in the XML or notes on it either.

Steve S.

**Comment by Gnurou** [comment]
Yeah, the canvas has an interesting size to say the least. Maybe it would be worth harmonizing all characters to something more intuitive, e.g. 100x100.
