### ISSUE TITLE
Specify Python version?

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#197]
I'm not sure what is wrong with the Python scripts but several of them basically don't compile any more:

$ python --version
Python 3.7.10
$ python harmonize-svg.py 
  File "harmonize-svg.py", line 55
    print "Error - no StrokeNumbers group for kanji %s (%s)" % (self.kanji, hex(kanjivg.realord(self.kanji)))
                                                           ^
SyntaxError: invalid syntax

$ python kanjivg.py 
  File "kanjivg.py", line 46
    print "realord warning: missing surrogate character"
                                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("realord warning: missing surrogate character")?
$ python kvg.py 
  File "kvg.py", line 45
    print "%s does not exist!" % (pFile,)
                             ^
SyntaxError: invalid syntax
$ python listmissingcomponents.py 
  File "listmissingcomponents.py", line 41
    print len(componentsList)
            ^
SyntaxError: invalid syntax

The other two, swap-strokes.py and xmlhandler.py, appear to still compile.

Is this a difference between Python 2 and Python 3?

At the very least the README file should specify what python to use.

**Comment by benkasminbullock** [comment]
After getting acquainted with the repository, these python scripts seem to be old maintenance scripts which were kept in the repository when the old directories they referred to were deleted. I think rather than updating them what should be done is to delete them completely, since the directories they manipulated have been deleted.

**Comment by Gnurou** [comment]
Sounds good to me, these are pretty old indeed and could probably easily be reproduced anyway.

**Comment by benkasminbullock** [comment]
I've removed the Python scripts in 0f6ce3db948086b2c6b4f3e752bd42523dd42602.
