### ISSUE TITLE
15 Jinmeiyou kanji missing from KanjiVG

### ISSUE THREAD

**Issue by BlueRaja** [KanjiVG/kanjivg#198]
There are 15 kanji from the list of ~850 [Jinmeiyou kanji](https://en.wikipedia.org/wiki/Jinmeiy%C5%8D_kanji) that are missing from KanjiVG:

> 俠 焰 禱 繡 繫 蠟 醬 顚 鷗 俱 吞 簞 蟬 瘦 錄

There's ~3000 kanji in the two lists of "acceptable" kanji released by the Japanese government. Given that KanjiVG supports over 6500 kanji, I was surprised that some entries from the official lists are missing.

**Comment by benkasminbullock** [comment]
On Tue, 4 May 2021 at 15:40, BlueRaja ***@***.***> wrote:

> There are 15 kanji from the list of ~850 Jinmeiyou kanji
> <https://en.wikipedia.org/wiki/Jinmeiy%C5%8D_kanji> that are missing from
> KanjiVG:
>
> 俠焰禱繡繫蠟醬顚鷗俱吞簞蟬瘦錄
>
> These aren't in the JIS level one and level two kanji, which is what
kanjivg consists of. For example, 俠 is in level 3 of JIS:

https://kanji.jitenon.jp/kanjim/6430.html

**Comment by BlueRaja** [comment]
Is that a hard rule? It would make sense for Kanji VG to support all the Jinmeiyou kanji.

It seems JIS 1 is meant to include all the Jinmeiyou kanji, so I'm not sure why these are in JIS 3.  Historical reasons?

**Comment by benkasminbullock** [comment]
> Is that a hard rule? It would make sense for Kanji VG to support all the Jinmeiyou kanji.

I agree that it would be better if it did.

> It seems JIS 1 is meant to include all the Jinmeiyou kanji, so I'm not sure why these are in JIS 3. Historical reasons?

A lot of them are 旧字体 (kyuujitai) which are older versions of existing characters, so it appears likely that they weren't included because a more modern variant was selected. I have a web page about it here:

https://www.sljfaq.org/afaq/kyuujitai.html

**Comment by benkasminbullock** [comment]
As it happens these already seem to be in the repository, but they are under different names. For example 吞 is available as [kanji/05451-Jinmei.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05451-Jinmei.svg). 

My own opinion is that the -Jinmei things should be moved to the correct Unicode code points.

**Comment by benkasminbullock** [comment]
My research so far indicates that we have 12 of these already:
```
俠 侠 *
焰 焔 kanji_mismatch/07114-Jinmei.svg
禱 祷 kanji_mismatch/07977-Jinmei.svg
繡 繍 kanji_mismatch/07e4d-Jinmei.svg
繫 繋 kanji/07e4b-Jinmei.svg
蠟 蝋 kanji_mismatch/0874b-Jinmei.svg
醬 醤 kanji/091a4-Jinmei.svg
顚 顛 kanji_mismatch/0985b-Jinmei.svg
鷗 鴎 kanji_mismatch/09d0e-Jinmei.svg
俱 倶 kanji/05036-Jinmei.svg
吞 呑 kanji/05451-Jinmei.svg
簞 箪 kanji_mismatch/07baa-Jinmei.svg
蟬 蝉 kanji_mismatch/08749-Jinmei.svg
瘦 痩 *
錄 録 *
```
I propose moving the Jinmei forms to the Unicode code point of the character on the left.

**Comment by benkasminbullock** [comment]
Please see https://github.com/KanjiVG/kanjivg/pull/268

**Comment by benkasminbullock** [comment]
The remaining work on this issue is to make forms for 俠 [侠], 瘦 [痩], and 錄 [録]. At the moment there aren't any "Jinmei" forms lurking in the kanji surrounded by square brackets, so unless they are lurking elsewhere, someone will have to create the vector forms.

**Comment by BlueRaja** [comment]
A handful of new ones with this issue, using the latest kanjidict values _(I'm assuming the list of jinmeiyou kanji got updated or something)_
```
德 步 歷 綠
```

**Comment by leehericks** [comment]
There are 863 jinmeiyo kanji including variants.

Some of these kanji are old variants of Joyo kanji and some are variants of jinmeiyo kanji.

I echo the sentiment of the original author that KanjiVG should cover both the 2136 Joyo kanji and the 863 jinmeiyo kanji as these are official government tables.

**Comment by benkasminbullock** [comment]
If anyone wants to contribute these forms then please do so. The reason they are not in the files is because nobody has done the work to create them.
