### ISSUE TITLE
Remove kvg:part and use kvg:number instead

### ISSUE THREAD

**Issue by Gnurou** [KanjiVG/kanjivg#20]

**Comment by coredumper** [comment]
What is the exact meaning behind both? The doc says:

> **part**
> Is used if all the strokes of a component do not all come in a row. In this case, two or more identical groups need to be defined, and the **part** attribute allows to number these groups and defined them as being part of the same component. **TODO: remove as it is redundant with the  number attribute**
>
> **number**
> Allows to identify a group if the element it includes is represented several times in the kanji. For instance,

But it is still unclear to me whether how `kvg:number` works and whether `kvg:part == kvg:number`, and if not how `kvg:part` works.

For the record, here is a rough overview of the current state.

* Lines including *only* `kvg:part`:
```ShellSession
$ grep -v kvg:number */*svg | grep kvg:part | grep -v CDATA | wc -l
6968
```
* Lines including *only* `kvg:number`:
```ShellSession
$  grep kvg:number */*svg | grep -v kvg:part | grep -v CDATA | wc -l
0
```

* Lines including both `kvg:number` and `kvg:part`:
```ShellSession
$ grep kvg:number */*svg | grep kvg:part | grep -v CDATA | wc -l
23
```

* More details about last one:
```ShellSession
$ grep kvg:number */*svg | grep kvg:part | grep -v CDATA
kanji/05716-Kaisho.svg: <g id="kvg:05716-Kaisho-g1" kvg:element="囗" kvg:part="1" kvg:number="1" kvg:radical="general">
kanji/05716-Kaisho.svg:         <g id="kvg:05716-Kaisho-g5" kvg:element="囗" kvg:part="1" kvg:number="2">
kanji/05716-Kaisho.svg:         <g id="kvg:05716-Kaisho-g7" kvg:element="囗" kvg:part="2" kvg:number="2">
kanji/05716-Kaisho.svg: <g id="kvg:05716-Kaisho-g8" kvg:element="囗" kvg:part="2" kvg:number="1" kvg:radical="general">
kanji/05716.svg:        <g id="kvg:05716-g1" kvg:element="囗" kvg:part="1" kvg:number="1" kvg:radical="general">
kanji/05716.svg:                <g id="kvg:05716-g5" kvg:element="囗" kvg:part="1" kvg:number="2">
kanji/05716.svg:                <g id="kvg:05716-g7" kvg:element="囗" kvg:part="2" kvg:number="2">
kanji/05716.svg:        <g id="kvg:05716-g8" kvg:element="囗" kvg:part="2" kvg:number="1" kvg:radical="general">
kanji/05b73.svg:                        <g id="kvg:05b73-g3" kvg:element="玄" kvg:part="1" kvg:number="1" kvg:partial="true">
kanji/05b73.svg:                        <g id="kvg:05b73-g8" kvg:element="玄" kvg:part="2" kvg:number="1" kvg:partial="true" kvg:position="left">
kanji/05b73.svg:                        <g id="kvg:05b73-g10" kvg:element="玄" kvg:part="1" kvg:number="2" kvg:partial="true" kvg:position="right">
kanji/06148.svg:                        <g id="kvg:06148-g3" kvg:element="玄" kvg:part="1" kvg:number="1" kvg:partial="true">
kanji/06148.svg:                        <g id="kvg:06148-g8" kvg:element="玄" kvg:part="2" kvg:number="1" kvg:partial="true" kvg:position="left">
kanji/06148.svg:                        <g id="kvg:06148-g10" kvg:element="玄" kvg:part="1" kvg:number="2" kvg:partial="true" kvg:position="right">
kanji/06ecb.svg:                        <g id="kvg:06ecb-g4" kvg:element="玄" kvg:part="1" kvg:number="1" kvg:partial="true">
kanji/06ecb.svg:                        <g id="kvg:06ecb-g7" kvg:element="玄" kvg:part="2" kvg:number="1" kvg:partial="true" kvg:position="left">
kanji/06ecb.svg:                        <g id="kvg:06ecb-g9" kvg:element="玄" kvg:part="1" kvg:number="2" kvg:partial="true" kvg:position="right">
kanji/078c1.svg:                        <g id="kvg:078c1-g5" kvg:element="玄" kvg:part="1" kvg:number="1" kvg:partial="true">
kanji/078c1.svg:                        <g id="kvg:078c1-g8" kvg:element="玄" kvg:part="2" kvg:number="1" kvg:partial="true" kvg:position="left">
kanji/078c1.svg:                        <g id="kvg:078c1-g10" kvg:element="玄" kvg:part="1" kvg:number="2" kvg:partial="true" kvg:position="right">
kanji/08332.svg:                <g id="kvg:08332-g2" kvg:element="玄" kvg:part="1" kvg:number="1" kvg:partial="true" kvg:radical="nelson">
kanji/08332.svg:                <g id="kvg:08332-g5" kvg:element="玄" kvg:part="2" kvg:number="1" kvg:partial="true" kvg:position="left" kvg:radical="nelson">
kanji/08332.svg:                <g id="kvg:08332-g7" kvg:element="玄" kvg:part="1" kvg:number="2" kvg:partial="true" kvg:position="right">
```

Thanks for any information you would be able to provide.

**Comment by ospalh** [comment]
Reading the definition of `part` and `number`, they sound quite different.
I think keeping them apart is a good idea.

@coredumper 
I think the idea is that kanjivg should use `number` e.g. for “品” with `element="口" number="1"`  `element="口" number="2"`   `element="口" number="3"` 
(森 is not as easy. You can group that as 木+林 rather then 木+木+木( [= nine](http://math-fail.com/2010/08/irish-math-joke.html)))
And `part` for example in 裏 the 衣 is split in two with a 里 between the parts. You get ` kvg:element="衣" kvg:part="1"` with another group¹ ` kvg:element="亠"` and later `kvg:element="衣" kvg:part="2"`²


¹The extra group is because of the limitations of XML, i guess.
²Maybe there is no element for those four strokes without the top element, or the inner group is missing in that file.

**Comment by Gnurou** [comment]
Yes, "number" can be seen as an ID for the case where a given component
appears several times. The purpose is different from "part".

In a better format, "part" would not need to exist, and "number" would be
replaced by something more flexible (if it cannot be dropped altogether).

**Comment by benkasminbullock** [comment]
I think this issue is resolved now. I've updated the documentation on the format page. Please reopen if not satisfied.
