### ISSUE TITLE
Issue in Stroke #7 of 備

### ISSUE THREAD

**Issue by YeezyYeezyWhatsGood** [KanjiVG/kanjivg#200]
It is displayed like (1) but I think for handwriting it should be displayed as (2)

![image](https://user-images.githubusercontent.com/28869518/156459241-3c4ce1fb-8f5b-482f-8870-72ff534e3d21.png)

**Comment by benkasminbullock** [comment]
Both the left and right hand formats are in this repository as kanji/05099.svg and kanji/05099-Hyougai.svg respectively.
<table>
<tr>
<td>
<img width=300 height=300 src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05099.svg">
<td>
<img width=300 height=300 src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05099-Hyougai.svg">
</table>

**Comment by mifunetoshiro** [comment]
https://github.com/KanjiVG/kanjivg/issues/157

**Comment by benkasminbullock** [comment]
According to [Ulrich Apel's post on the KanjiVG mailing list](https://groups.google.com/g/kanjivg/c/iA7ofbeYxJw/m/HVBPkL9lAgAJ), the base model for KanjiVG is the schoolbook font. The bug report above mentions Mincho fonts etc., but we should be checking the schoolbook font based on handwritten form to see which form is right for KanjiVG. Googling gets me [this page](https://www.kkjn.jp/page-10/page-0-796), which gives the image 
<img src="https://www.kkjn.jp/svgz/50795.svgz">
This suggests quite strongly that #157's fix was incorrect and that @YeezyYeezyWhatsGood  is correct about this. Does anyone else want to chip in or should we just reverse these two?
