### ISSUE TITLE
Kanji 噓 is missing

### ISSUE THREAD

**Issue by NovaNix** [KanjiVG/kanjivg#201]
The kanji search feature on the website does not show a result for this kanji, and I don't think I was able to find it by searching the list for the hex code either.

**Comment by NovaNix** [comment]
Ah, that makes sense. Should I close the issue?

**Comment by benkasminbullock** [comment]
> Ah, that makes sense. Should I close the issue?

I can't close it, since I'm not a member of the KanjiVG team, so it's up to you as far as I'm concerned.

**Comment by Gnurou** [comment]
@benkasminbullock shall I make you a member of the team?

**Comment by benkasminbullock** [comment]
I thought I'd replied to the above but apparently not.

I think I can do something useful here if you add me so please do so.

**Comment by Gnurou** [comment]
Done - your help is appreciated. Closing this issue.
