### ISSUE TITLE
乡 or 幺 in element 雍

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#212]
The element on the lower left of 雍 is given as 幺 in four of the "standard" kanji:

kvg:058c5-g4
kvg:064c1-g5
kvg:07515-g4
kvg:096cd-g3

The bottommost stroke is identified sometimes as ㇔ in 07515 and sometimes as ㇒/㇔ in 064c1.

I think it would be better to change this to 乡 as the element, and be consistent in using ㇒.

I can write a script to automatically edit these all but before doing so, is there any objection to this?

**Comment by benkasminbullock** [comment]
This is fixed by the following pull request:

https://github.com/KanjiVG/kanjivg/pull/221

**Comment by benkasminbullock** [comment]
I've merged this into the master branch now. I hope I'm not going too fast with these changes, but a lot of work remains to do, so leaving lots of minor changes hanging would make things very confusing I think.

**Comment by Gnurou** [comment]
Just took a quick look and this looks good to me ; although 乡 is only used in 5 kanji total so maybe the use of 幺 was on purpose for some (etymological?) reason.

In any case it would be easy to sed back to 幺, so the change looks good.

The pace is indeed more than I can follow, but I'll try to review these little by little. :)

**Comment by Gnurou** [comment]
Actually [per the format description](https://kanjivg.tagaini.net/format.html) the `element` should be as physically close to the group it represents as possible, so this change looks correct. Maybe 幺 could be added as an `original` attribute, but I am not qualified to make that call unfortunately.
