### ISSUE TITLE
Add 茨, 牙, 韓, 𠮟, 栃,  淫, 葛, 僅, 煎, 詮, 嘲, 捗, 溺, 塡, 賭, 剝, 箸, 蔽, 頰, 餌, 遡, 遜, 謎, 餅 Joyo Kanji stroke order in color

### ISSUE THREAD

**Issue by KanjiBoy613** [KanjiVG/kanjivg#229]
Please add the Joyo Variants above according to Wikipedia and Jisho in color. Warning: Some of these Kanji on Jisho.org might not appear, so copy and paste!

**Comment by benkasminbullock** [comment]
@KanjiBoy613 In case I wasn't being clear enough, I was trying to ask if you could clarify your request a bit. I haven't checked all of them, but many of the characters you asked for are already in this repository. The rest of your request is not too clear either. 

I'll close this issue for now, but you can reopen it if you want to.
