### ISSUE TITLE
Static Download Link

### ISSUE THREAD

**Issue by sharikov** [KanjiVG/kanjivg#24]
Would it be possible to change the package download links to a static one?  Or create separate links?  This would make it easier to sync to the latest.  All the other dictionary sources like jmdict, jmnedict, kanjidicand etc provide the latest static links.

For example, change:

```
 https://github.com/downloads/KanjiVG/kanjivg/kanjivg-20120219.xml.gz
```

to:

```
 https://github.com/downloads/KanjiVG/kanjivg/kanjivg-current.xml.gz
```

Under the link already includes the upload date, so people won't be confused.  

Thank you.

**Comment by ospalh** [comment]
There is of course the permanent link to the [latest](https://github.com/KanjiVG/kanjivg/releases/latest) release.

**Comment by benkasminbullock** [comment]
This seems to be resolved, let's close this.
