### ISSUE TITLE
Remove 巫 grouping?

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#257]
I wonder if the 巫 工 grouping in kanji/06aa3.svg and related characters is actually necessary?

```
	<g id="kvg:06aa3-g2" kvg:element="嗇" kvg:position="right">
		<g id="kvg:06aa3-g3" kvg:element="巫" kvg:variant="true" kvg:position="top">
			<g id="kvg:06aa3-g4" kvg:element="工" kvg:part="1" kvg:variant="true">
				<g id="kvg:06aa3-g5" kvg:element="土" kvg:part="1">
					<path id="kvg:06aa3-s5" kvg:type="㇐" d="M47.12,26.19c0.93,0.41,3.96,0.54,4.9,0.42c4.37-0.56,29.96-2.46,37.3-2.89c1.43-0.08,2.74,0.08,3.92,0.43"/>
					<path id="kvg:06aa3-s6" kvg:type="㇑" d="M67.46,13c1.57,2.01,1.57,3.22,1.57,4.83c0,6.17-0.05,28.92-0.05,36.92"/>
				</g>
			</g>
			<g id="kvg:06aa3-g6" kvg:element="从">
				<g id="kvg:06aa3-g7" kvg:element="人" kvg:position="left">
					<path id="kvg:06aa3-s7" kvg:type="㇒" d="M54.64,33.99c0.11,0.41,0.08,1.31-0.07,1.77c-1.48,4.49-3.81,10.33-8.38,14.61"/>
					<path id="kvg:06aa3-s8" kvg:type="㇏" d="M55.68,41.41c2.21,1.2,5.04,4.38,6.12,7.4"/>
				</g>
				<g id="kvg:06aa3-g8" kvg:element="人" kvg:position="right">
					<path id="kvg:06aa3-s9" kvg:type="㇒" d="M85.22,30.74c0.12,0.42,0.09,1.35-0.08,1.83c-1.68,4.62-4.31,10.65-9.47,15.06"/>
					<path id="kvg:06aa3-s10" kvg:type="㇏" d="M84.65,39.88c2.82,1.24,6.41,4.54,7.78,7.67"/>
				</g>
			</g>
			<g id="kvg:06aa3-g9" kvg:element="工" kvg:part="2" kvg:variant="true">
				<g id="kvg:06aa3-g10" kvg:element="土">
					<path id="kvg:06aa3-s11" kvg:type="㇐" d="M46.25,56.21c0.67,0.22,3.04,0.45,4.17,0.35c12.14-1.09,30.89-2.71,41.94-3.04c1.81-0.05,3.99,0.37,4.89,0.72"/>
				</g>
			</g>
		</g>
```
Visually that is not the same as 巫. I suppose it could be useful as a placeholder though, I cannot see what good having a 工 group is when that doesn't even exist. The following files all contain this stuff:

kanji/058bb.svg
kanji/06aa3-Kaisho.svg
kanji/06aa3.svg
kanji/07246.svg
kanji/07a61-Kaisho.svg
kanji/07a61.svg
kanji/08262.svg
kanji/08594.svg

**Comment by weirdalsuperfan** [comment]
What's the harm...? The more the merrier. I for one like to see these kinds of relationships. Even if it "doesn't exist," it DOES exist visually.  If it ain't broke don't fix it.

Love seeing all the recent activity btw

**Comment by benkasminbullock** [comment]
> What's the harm...?

The harm, I suppose, is the unnecessary groups, and the incorrect elements, especially the group of 工, which is both incorrect and seems to add nothing much. The upper element which actually appears here only appears in one other Unicode 䘮 where it isn't above 回. Anyway, it probably isn't really worth removing it.

> The more the merrier. I for one like to see these kinds of relationships. Even if it "doesn't exist," it DOES exist visually. If it ain't broke don't fix it.

Well, to be pedantic, it doesn't really exist visually. There is no 工, it is 土 at the top. That's why I was wondering whether to remove it. But as you say it is harmless.

**Comment by benkasminbullock** [comment]
If no-one else has anything to add, I'll close this without taking any action. It can be reopened again later if anyone else is concerned.
