### ISSUE TITLE
kanji/0881f.svg isn't U+881f nor is it 蝋

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#281]
<img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0881f.svg" width=327 height=327>

kanji/0881f doesn't seem to represent the Unicode code point 蠟 since it's missing the top 巛 and the centre right should be 龱. The kvg:element on the topmost group of the paths has a value of 蝋 but it isn't that either.

**Comment by benkasminbullock** [comment]
Using IDSGrep I was able to find that this is U+27491. There is little information about the character, e.g. Wiktionary is blank. https://en.wiktionary.org/wiki/%F0%A7%92%91

**Comment by SlugFiller** [comment]
This character was added in c0a02f3a90a1c700d4002e391c319a274272de66, but I'm not sure where it came from since it doesn't match any of the deleted files.

**Comment by benkasminbullock** [comment]
> This character was added in [c0a02f3](https://github.com/KanjiVG/kanjivg/commit/c0a02f3a90a1c700d4002e391c319a274272de66), but I'm not sure where it came from since it doesn't match any of the deleted files.

It was moved from kanji_mismatch/0881f-Jinmei.svg to its current code point in that commit, but that seems to be an error, since it doesn't match that code point either. I don't know why but git says that the file was deleted and the other file created, rather than recording that as a move of a file. Presumably because all the internal IDs changed git doesn't recognise it as the same file. I guess the thing to do is to move the file, commit, then change the IDs, then commit again.
