### ISSUE TITLE
Various kvg:phon element value meanings are unclear

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#312]
kanji/05951.svg has a meaningless/undocumented kvg:phon value of "2+3+2+6+刀".

**Comment by benkasminbullock** [comment]
Similarly kanji/061b2.svg has kvg:phon="宀+2+3+2+2+罒". I guess there are a lot more of these.

**Comment by benkasminbullock** [comment]
This is a more or less complete list of these things:
```
kanji/04ee5.svg:	<g id="kvg:04ee5-g1" kvg:position="left" kvg:phon="3+6+1">
kanji/04faf.svg:	<g id="kvg:04faf-g2" kvg:position="right" kvg:phon="11+2+矢">
kanji/05951.svg:	<g id="kvg:05951-g1" kvg:position="top" kvg:phon="2+3+2+6+刀">
kanji/061b2.svg:	<g id="kvg:061b2-g1" kvg:position="top" kvg:phon="宀+2+3+2+2+罒">
kanji/06e0b.svg:	<g id="kvg:06e0b-g2" kvg:position="right" kvg:phon="止+冫+4+1">
kanji/07121.svg:	<g id="kvg:07121-g1" kvg:position="top" kvg:phon="丿+2+一+3+3+3+3+2">
kanji/0821e.svg:	<g id="kvg:0821e-g1" kvg:position="top" kvg:phon="丿+2+一+3+3+3+3+2">
kanji/08a89.svg:	<g id="kvg:08a89-g1" kvg:position="top" kvg:phon="つ+2+八">
kanji/09006.svg:	<g id="kvg:09006-g1" kvg:phon="1+4+2+屮">
kanji/09042.svg:	<g id="kvg:09042-g1" kvg:phon="1+4+豕">
kanji/09063.svg:	<g id="kvg:09063-g1" kvg:phon="中+2+3+11+2+11+2">
kanji/0968a.svg:	<g id="kvg:0968a-g2" kvg:position="right" kvg:phon="1+4+豕">
kanji/0970a.svg:	<g id="kvg:0970a-g1" kvg:element="雨" kvg:variant="true" kvg:position="top" kvg:radical="general" kvg:phon="雨+2/1">
kanji/0970a.svg:			<g id="kvg:0970a-g4" kvg:position="top" kvg:phon="雨+2/2">
```

**Comment by benkasminbullock** [comment]
In place of this bug report, I've made a note here:

https://kanjivg.tagaini.net/known-problems#kvg-phon-undocumented

It would make sense to simply remove the kvg:phon attributes, since their current use is arbitrary, inconsistent and undocumented.

**Comment by EveTrudy** [comment]
2 means _yoko_, 3 means _tate_, 5 means _hane_, and so on. Each number represents a stroke type.
“つ” means “ツ”.

**Comment by benkasminbullock** [comment]
Even if the numbers have a meaning of some kind, they are inconsistently applied to the data, which means nobody can use them for anything. The only way keeping the numbers would make sense would be if someone was to add all the numbers to all the data consistently and document what they meant. I don't see anybody volunteering to do that, so the best thing really is to remove the partial addition.
