### ISSUE TITLE
Group nyo counterparts into a single group

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#337]
Currently where there is a group with `kvg:position="nyo"`, the counterpart of the element may consist not of a single group, but of multiple groups. This makes manipulation of the data more inconvenient as well as making comparision with sources such as IDS more fraught. Thus I suggest grouping all of the counterpart elements of `nyo` into a single group consistently throughout KanjiVG. This was discussed in a proposal here:

https://groups.google.com/g/kanjivg/c/R2qdhAGnABY/m/R5FsXNd9zOQJ

and possibly elsewhere.

In the above suggestion, @mskala suggested giving them the position value `nyo-inside`. I'd like to suggest a simpler `nyoc` as an abbreviation for nyo-counterpart. This could also be applied to `tarec` etc.

**Comment by benkasminbullock** [comment]
Similarly, this groups the counterpart/complement of the tare element into a new position grouping `tarec`:

https://github.com/KanjiVG/kanjivg/pull/339

**Comment by benkasminbullock** [comment]
If there are no objections I'll just go ahead with this.

**Comment by mskala** [comment]
On Sat, 23 Apr 2022, Ben Bullock wrote:
> If there are no objections I'll just go ahead with this.

It sounds reasonable to me.

If the counterpart contains non-consecutive strokes (for instance, if it
includes strokes 3, 4, and 6, but not 5) then it may not be possible to
add a group containing all and only its strokes.  That bears on the
comment I've made before about how it would be nice to record stroke
numbers explicitly in an attribute and end the requirement for strokes to
be stored in sequential order in the file.  It is a general problem,
created by the sequential order requirement, that you can't add an XML
group for a visual or semantic grouping of strokes, if it does not
coincide with a consecutive interval of stroke numbers.

But I don't know that specific examples of that problem exist for nyo and
tare counterparts in particular; I'd expect such situations to be rare.

-- 
Matthew Skala
***@***.***                 People before tribes.
https://ansuz.sooke.bc.ca/

**Comment by benkasminbullock** [comment]
> It sounds reasonable to me.

Thank you for replying.

> If the counterpart contains non-consecutive strokes (for instance, if it includes strokes 3, 4, and 6, but not 5) then it may not be possible to add a group containing all and only its strokes.

There might be cases like that but I didn't find any. I noticed your comment on that topic in the link above as well. At the moment KanjiVG uses <a href="https://kanjivg.tagaini.net/svg-format.html#part">part</a> to indicate those non-contiguous groups. 

> That bears on the comment I've made before about how it would be nice to record stroke numbers explicitly in an attribute and end the requirement for strokes to be stored in sequential order in the file. It is a general problem, created by the sequential order requirement, that you can't add an XML group for a visual or semantic grouping of strokes, if it does not coincide with a consecutive interval of stroke numbers.

KanjiVG does have such groups, for example radicals are added which consist of more than one `g` element. See [kanji/066f2.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/066f2.svg) for example.

> But I don't know that specific examples of that problem exist for nyo and tare counterparts in particular; I'd expect such situations to be rare.

I did not notice any. But the current set of edits were done largely using a simplistic script rather than careful checking. If such cases exist they may be resolved by use of the `kvg:part` attribute. 

I think that it is better to get the bulk of these problems fixed, the documentation and the files made more consistent, and then hopefully any remaining problems will be cured by individual people noticing them.
