### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by KanjiBoy613** [KanjiVG/kanjivg#391]
A) Add grids to each character and change the stroke width to 1.
B) Add stroke order diagrams according to my suggestions. First, the kanji should be all gray, and in the end, the kanji should be all black. Each new stroke should be green with a red beginning.
C) Connect stroke 25 to stroke 26 on u9b31 so that they are perpendicular and joined together. Do the same for stroke 2 and 3 of u5973 so that they are not intersecting.

**Comment by benkasminbullock** [comment]
Thanks for the suggestions.

**Comment by KanjiBoy613** [comment]
Uh, those weren’t suggestions, they were more like requests that you should do soon.

**Comment by benkasminbullock** [comment]
Thank you for the requests. However, I've already responded with a refusal to your other request about the grids, and your previous request for colour changes.

Request C for changes to the structure of the kanji would require a reference to an authoritative source showing that your proposed change is correct and the current KanjiVG data is wrong.
