### ISSUE TITLE
Stroke order of \u754b 畋

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#392]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/0754b.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0754b.svg" width="327" height="327"></a>

Strokes 8 and 9 are flipped. In 524833a3aac70443e9ff068d847bf67a768bab11 their tags were changed to match the path, but clearly the issue was with the paths, as evident from both the radical, and the following two sources:

https://kaku-navi.com/kanji/kanji10060.html
https://kakijun.jp/page/dent09200.html

**Comment by benkasminbullock** [comment]
Thank you for this bug report. 81a474a2e9ad8995dde8a5a85f46ef1421d1d60f should fix this. Please reopen if not satisfied.
