### ISSUE TITLE
Stroke order of \u71ee 燮

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#393]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/071ee.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/071ee.svg" width="327" height="327"></a>

The 言 radical should be first in the stroke order, but instead it is written between the left and right 火.

IDS shows it as ⿶⿱炏又言. Also, the following two sources show the same order:
https://kakijun.jp/page/yawa17200.html
https://kaku-navi.com/kanji/kanji09199.html

**Comment by benkasminbullock** [comment]
Thank you for reporting this. It should be resolved by ba740547ca4de6fd86dc2ab23c8cc65b929e0f2b. Please reopen if not satisfied.
