### ISSUE TITLE
Stroke order of \u63d2 插

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#394]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/063d2.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/063d2.svg" width="327" height="327"></a>

Strokes 11 and 12 are flipped. See sources:
https://kakijun.jp/page/9D87200.html
https://kaku-navi.com/kanji/kanji05587.html

**Comment by SlugFiller** [comment]
The issue exists in 歃 \u6B43 as well

**Comment by benkasminbullock** [comment]
Thank you for reporting this. It should be fixed with 129c88162. Please reopen if not satisfied.
