### ISSUE TITLE
Stokes 6 and 7 of \u754c 界

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#395]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/0754c.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0754c.svg" width="327" height="327"></a>

Strokes 6 and 7 should be connected at the top. See contained kanji:
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/04ecb.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/04ecb.svg" width="327" height="327"></a>
And also containing kanji:
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/0583a.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0583a.svg" width="327" height="327"></a>

**Comment by benkasminbullock** [comment]
One can easily find counterexamples. https://www.google.com/search?q=%E7%95%8C+%E6%A5%B7%E6%9B%B8

Please provide a source from [the references](http://kanjivg.tagaini.net/ref.html) or similar if you want to reopen this.
