### ISSUE TITLE
Use of kanjivg without acknowledgement

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#396]
This site:

https://mojinavi.com/d/u63d2

appears to be using the kanjivg graphics without acknowledgement. 

I can't find anything on their page about KanjiVG:

https://mojinavi.com/policy

The animated stroke order graphic clearly comes from KanjiVG.

**Comment by chonxn4** [comment]
I used kanjivg in an APK (not this website above) for Android. I put cc
by-sa icon and 1 sentence noting copyright by Ulrich. Is that enough for me
to trade the app on store?

Ty

**Comment by benkasminbullock** [comment]
On Sun, 19 Jun 2022 at 17:51, chonxn4 ***@***.***> wrote:

> I used kanjivg in an APK (not this website above) for Android. I put cc
> by-sa icon and 1 sentence noting copyright by Ulrich. Is that enough for me
> to trade the app on store?
>
> Ty
>

Ask on the mailing list.

**Comment by benkasminbullock** [comment]
Presumably the copyright holder doesn't care about this issue so I'm closing it.
