### ISSUE TITLE
爲 \u7232 stroke 9, 偽 \u507d stroke 8, 僞 \u50de stroke 11

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#397]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/07232.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/07232.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/0507d.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0507d.svg" width="327" height="327"></a>
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/050de.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/050de.svg" width="327" height="327"></a>

The first stroke of radical 灬 in all the above is drawn as ㇔, when it should be drawn as ㇒. This containing kanji has it drawn in the opposite direction:

<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/08b4c.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/08b4c.svg" width="327" height="327"></a>

Various sources seem to offer both variants. In an attempt to find something authoritative, I looked for a copy of JISX0208, but a PDF of it costs like 4 video games, so I found a PDF of its predecessor JISC 6226-1978 instead. 偽 appears on page 4 (table 1, row 21, column 22), 僞 appears on page 8 (table 5, row 49, column 6), and 爲 appears on page 12 (table 9, row 64, column 10). All of them are in the latter form.

I've also found these characters in an IBM specification of Japanese Extended Unix Code from 2001. In it, 偽 agrees with the KanjiVG appearance, but 僞 and 爲 do not.

Barring another, more authoritative source, on how the characters should appear, I believe this should be changed.

**Comment by benkasminbullock** [comment]
The element ㇔ CJK STROKE D is actually the correct stroke for all of the elements of 灬.  I've documented this at http://kanjivg.tagaini.net/stroke-types.html. Please see reference https://unicode.org/wg2/docs/n3063.pdf for confirmation. One error I made in the early stages of working with KanjiVG was to change `kvg:type` for these elements from CJK STROKE D, but then I realised that it was a mistake and changed them all back.

**Comment by SlugFiller** [comment]
Specifically, it appears to be D variant, but I'm referring specifically to the appearance.

**Comment by benkasminbullock** [comment]
The references used to make the original drawings are listed [here](http://kanjivg.tagaini.net/ref.html) so if you want to change it please justify by showing that the original fonts which KanjiVG was based on support that change. 

For the time being I'll close this issue since it hasn't had any activity for over six months.
