### ISSUE TITLE
Stroke order of \u88f2 裲

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#398]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/088f2.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/088f2.svg" width="327" height="327"></a>

Strokes 10 through 13 are flipped. See contained kanji:

<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/05169.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05169.svg" width="327" height="327"></a>

And also sources:
https://kakijun.jp/page/E5EA200.html
https://kaku-navi.com/kanji/kanji15091.html

**Comment by benkasminbullock** [comment]
Thank you for pointing this out. It should be fixed in 0700d0721. Let us know if not.
