### ISSUE TITLE
Stroke order of \u85a9 薩

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#399]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/085a9.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/085a9.svg" width="327" height="327"></a>

Strokes 9 and 10 are swapped. Should be the same as 文.

See:
https://kakijun.jp/page/satu17200.html

(kaku-navi has the stroke order from before the JIS2004 update, which has 立 as the shape instead)

**Comment by benkasminbullock** [comment]
Thank you for reporting, see 1a49ada92. Please reopen if not OK as before.
