### ISSUE TITLE
Change handling of 辶 radical in 人名用 and 表外字 kanji

### ISSUE THREAD

**Issue by dddlr** [KanjiVG/kanjivg#402]
In KanjiVG, the 辶 radical in 人名用漢字 contains two dots (like 丶丶乛乛乀) instead of one (丶乛乛乀). I'd like to suggest changing the 辶 radical in all 人名用漢字 to one dot only, and treating the two-dot versions as a variant in these kanji. This would allow the stroke order images to match with how 教科書体 would typically display these kanji, and presumably how people are expected to write them.

I tested some 教科書体 fonts with the following phrase: 進道遁迄邂遞. This contains two 常用, two 人名用, and two 表外 kanji. The following typefaces all use only one dot for the 辶 in 常用漢字 and 人名用漢字, but use two dots for 表外漢字:

* [AR教科書体M](https://designpocket.jp/dl_font_category/detail.aspx?bid=3114) uses one dot for 常用漢字 and 人名用漢字, but two dots for 表外漢字
* [イワタ中太教科書体](https://designpocket.jp/dl_font_category/detail.aspx?bid=16317) gives the same results as AR教科書体M above
* [モトヤ教科書](https://www.motoyafont.jp/font-list/kyotai.html) 

[UDデジタル教科書体 M](https://www.morisawa.co.jp/fonts/specimen/3763) is unique in that it uses one dot for all cases, following the [常用漢字 convention](https://web.archive.org/web/20130612203642/http://www.bunka.go.jp/bunkashingikai/soukai/pdf/kaitei_kanji_toushin.pdf) for handwritten kanji.

With this in mind, and with how one-dot 辶 is the only(?) standard handwritten form for all 常用漢字, I think it would also be ideal (but not necessary) to add the one-dot version as an alternate version or variant for all 表外 kanji too.

**Comment by benkasminbullock** [comment]
KanjiVG already has these, for example [kanji/09041-Hyougai.svg](http://www.lemoda.net/kvg/09041-Hyougai.svg).

**Comment by dddlr** [comment]
Ah, thanks for bringing it up! I wasn't able to see the `-Hyougai.svg` files in the GitHub file list :sweat_smile: 

Would it be possible to set all 人名用漢字 to use the one-dot version by default, as it looks like almost(!) all 教科書体 fonts use the one-dot version for these? This includes all of the typefaces listed above, as well as _A-OTF Kyoukasho ICA Pro L_ (one of the typefaces that was used as references for the KanjiVG data -- the other typeface, _DFKyoKaSho-W3-MP-RKSJ-H_, seems to be a lone exception here).

For example, for 迄: [08fc4-Hyougai.svg](https://www.lemoda.net/kvg/08fc4.svg) would be renamed to [08fc4.svg](https://www.lemoda.net/kvg/08fc4.svg), and [08fc4.svg](https://www.lemoda.net/kvg/08fc4.svg) could perhaps be renamed to `08fc4-Kaisho.svg`. or something else that's more appropriate.

**Comment by benkasminbullock** [comment]
At the moment it is quite difficult to navigate the files to know what is there, and it's almost impossible to see the groups and stroke types. I've done some work on that in providing the above KanjiVG viewer on my web site, but as yet it is not indexable nor searchable. The main kanjivg.tagaini.net site does not allow any viewing of the variants yet. These are important for project health going forward in my opinion, so it would be better if we had some sort of central facility for indexing all of the files so that people would know what is in them.

As far as changing which files have which names, you would probably have to bring that up on the mailing list and discuss your proposed changes there, rather than putting them in a bug report on github.

**Comment by SlugFiller** [comment]
I wish to point out that KanjiVG is based on JIS, and in 2004, several character appearances have been explicitly set to double dot. For instance: 逢 was changed from single to double dot. The default appearance should most likely remain consistent with latest JIS. Although, one could argue that the 2004 appearance is JIS X 0213, and KanjiVG only covers the earlier JIS X 0208 (last release in 1978). However, other characters (e.g. 篝) are also consistent with the 2004 appearance, so this should probably remain as-is.

More info on characters modified in 2004:
https://kakijun.jp/main/jis2004.html

**Comment by benkasminbullock** [comment]
Which sources we should regard as authoritative and use as authoritative references should be discussed and decided on the KanjiVG mailing list rather than on the github issues page, so please bring it up there.

**Comment by benkasminbullock** [comment]
I'll close this issue for now since it hasn't been discussed any further.
