### ISSUE TITLE
樅 stroke 13 is backwards

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#403]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/06a05.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/06a05.svg" width="327" height="327"></a>

Stroke 13 goes from right to left. Clearly, it's supposed to go from left to right.

**Comment by SlugFiller** [comment]
Same in 嚔 stroke 16
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/05694.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05694.svg" width="327" height="327"></a>

**Comment by SlugFiller** [comment]
Same in 蹤 stroke 16:
[<img alt="" width="327" height="327" src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/08e64.svg">](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08e64.svg)

**Comment by SlugFiller** [comment]
Same in 鉦 stroke 11:
[<img alt="" width="327" height="327" src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09266.svg">](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09266.svg)

**Comment by SlugFiller** [comment]
Same in 徙 stroke 9:
[<img alt="" width="327" height="327" src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05f99.svg">](https://github.com/KanjiVG/kanjivg/blob/master/kanji/05f99.svg)

**Comment by SlugFiller** [comment]
Same in 慫 stroke 9:
[<img alt="" width="327" height="327" src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/0616b.svg">](https://github.com/KanjiVG/kanjivg/blob/master/kanji/0616b.svg)

**Comment by benkasminbullock** [comment]
I've confirmed the top one is in the wrong direction.

**Comment by benkasminbullock** [comment]
Thank you for reporting this. These should all be fixed by 23af80c44. Please reopen if not satisfied.

c curves were replaced with C curves in several cases, it should not be a problem.
