### ISSUE TITLE
鬮 stroke order

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#404]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/09b2e.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09b2e.svg" width="327" height="327"></a>

Strokes 17 and 18 are flipped.

See contained radical:

<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/09f9c.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/09f9c.svg" width="327" height="327"></a>

**Comment by benkasminbullock** [comment]
See 13d2a6800
