### ISSUE TITLE
Stroke count doesn't coincide for several radicals 

### ISSUE THREAD

**Issue by syt0r** [KanjiVG/kanjivg#408]
My script also found several places where strokes count for the same radical doesn't coincide and there is no part/partial/variant attributes used:

Attention! Radical 己 has multiple variants: 3 strokes in characters[5df7巷,5dfd巽,5dfd巽,5df1己,5dfb巻,6539改,5fcc忌], 4 strokes in characters[5df4巴]
Attention! Radical 牙 has multiple variants: 4 strokes in characters[7259牙,9d09鴉], 5 strokes in characters[90aa邪,96c5雅]
Attention! Radical 飠 has multiple variants: 8 strokes in characters[9928館], 9 strokes in characters[8755蝕]

I wasn't sure how to fix them

**Comment by benkasminbullock** [comment]
> Attention! Radical 己 has multiple variants: 3 strokes in characters[5df7巷,5dfd巽,5dfd巽,5df1己,5dfb巻,6539改,5fcc忌], 4 strokes in characters[5df4巴]

5df4 has an error where stroke 2 is wrongly included in that shape.

This issue should be fixed by https://github.com/KanjiVG/kanjivg/commit/6677d543e00c69ce22f49f5ed3d8d2a7fa45532d

**Comment by benkasminbullock** [comment]
> Attention! Radical 牙 has multiple variants: 4 strokes in characters[7259牙,9d09鴉], 5 strokes in characters[90aa邪,96c5雅]

This is due to the two different ways of writing this element, one with the left down stroke and the centre horizontal as one line, and one as two lines.

**Comment by benkasminbullock** [comment]
> Attention! Radical 飠 has multiple variants: 8 strokes in characters[9928館], 9 strokes in characters[8755蝕]

Similar to the above.

**Comment by syt0r** [comment]
I see. Initially I was trying to extract all possible standard radicals from dataset, but these characters failed my validation. 

By the way I see there is separate radical for𩙿, right next to 飠 here: https://www.unicode.org/charts/nameslist/n_2E80.html
Maybe we can use it instead? As I understood from kanjivg's website as long as it's not from kangix it's ok

For 牙 it's a bit funny, seems like 5 strokes variant is korean version according to wiktionary, and when `lang` attribute in html is used the difference is noticeable)) https://ja.wiktionary.org/wiki/%E7%89%99

![image](https://user-images.githubusercontent.com/7478653/211221958-046d8d20-1d74-4935-9d26-4942f9715d34.png)
![image](https://user-images.githubusercontent.com/7478653/211221993-61c4d707-de4c-42c8-9260-a11e12713809.png)

**Comment by benkasminbullock** [comment]
> I see. Initially I was trying to extract all possible standard radicals from dataset, but these characters failed my validation.
> 
> By the way I see there is separate radical for𩙿, right next to 飠 here: https://www.unicode.org/charts/nameslist/n_2E80.html Maybe we can use it instead? As I understood from kanjivg's website as long as it's not from kangxi it's ok

Yes it's OK to change to using U+2E8E as mentioned here:

http://kanjivg.tagaini.net/radicals.html

This change should do that job:

https://github.com/KanjiVG/kanjivg/commit/88d53d05f40f0daa9af9e72905f085c7a714eeb9

In the above you have used U+2967F so I got a bit confused searching for your text.

**Comment by syt0r** [comment]
Great, thanks for updates!
