### ISSUE TITLE
Incorrect stroke order for 潟

### ISSUE THREAD

**Issue by lgtk** [KanjiVG/kanjivg#415]
Based on Japanese sources, strokes 6 and 7 should be reversed. This kanji is on the Joyo list since 2010 and appears on Kanji Kentei tests where stroke order is tested, and KanjiVG’s order would produce incorrect answers.

Example source: https://kaku-navi.com/kanji/kanji08544.html

**Comment by benkasminbullock** [comment]
On Sun, 29 Jan 2023 at 09:26, lgtk ***@***.***> wrote:

> Based on Japanese sources, strokes 6 and 7 should be reversed. This kanji
> is on the Joyo list since 2010 and appears on Kanji Kentei tests where
> stroke order is tested, and KanjiVG’s order would produce incorrect answers.
>
Please clarify this. The current stroke order is this:

[image: stroke-order-06f5f.png]

See https://www.lemoda.net/kvg/kanji/06f5f.svg.

> Example source: https://kaku-navi.com/kanji/kanji08544.html
>
I've checked three times and this has strokes 6 and 7 in the same order as
the above current version of KanjiVG.

Possible reasons why you're seeing something else:

* There is a variant file, called kanji/06f5f-HzLst.svg, with a different
stroke order. Here HzLst in the name means the "horizontal" part comes
"last". See http://kanjivg.tagaini.net/variants.html for a full explanation
of variant forms in kanjivg.

* You're using an old version of the file. Its stroke order was changed in
April 2022.

https://github.com/KanjiVG/kanjivg/commits/master/kanji/06f5f.svg
https://github.com/KanjiVG/kanjivg/commit/fa4a09ac8774ca8eea4b9d11a2cfe9d59c7a2674#diff-af54c28a4a47d0840073f16bd44c936ad211a2d897586390f2c9fe476af12340

Please can you clarify this and get back to us?

**Comment by lgtk** [comment]
Thanks for investigating.

Your linked “current stroke order” is correct, but on kanjivg’s home page, if you click “Listing” then click on 潟 it takes you to the page below which shows the incorrect order:

http://kanjivg.tagaini.net/viewer.html?kanji=潟

Maybe that page should be updated?

(Also I originally came about this in the iPhone app called “Japanese” by japaneseapp.com but their app was last updated 3 years ago so probably nothing can be done…)

**Comment by benkasminbullock** [comment]
On Sun, 29 Jan 2023 at 10:46, lgtk ***@***.***> wrote:

> Thanks for investigating.
>
> Your linked “current stroke order” is correct,
>

Thank you for clarifying. This issue is closed now.


> but on kanjivg’s home page, if you click “Listing” then click on 潟 it
> takes you to the page below which shows the incorrect order:
>
> http://kanjivg.tagaini.net/viewer.html?kanji=潟
>
> Maybe that page should be updated?
>

Investigating, the page https://github.com/KanjiVG/kanjivg.github.com seems
to rely on some kind of sub module or sub repository link which has to be
manually updated with the latest version of kanjivg, which is a nuisance.
I'll open this as a separate issue.


> (Also I originally came about this in the iPhone app called “Japanese” by
> japaneseapp.com but their app was last updated 3 years ago so probably
> nothing can be done…)
>
We're not responsible for upstream projects which use this data, so please
ask them directly.
