### ISSUE TITLE
关 element

### ISSUE THREAD

**Issue by mikemorr** [KanjiVG/kanjivg#425]
关 is listed as an element in 関 and 咲, but I think 送, 朕, and 渕 could/should also include it.

**Comment by benkasminbullock** [comment]
This should be complete with https://github.com/KanjiVG/kanjivg/commit/14048e27809d1850c2ab5ccdce250800e06adbc6

**Comment by benkasminbullock** [comment]
Thank you for the report. Please let us know if you find other things.
