### ISSUE TITLE
Consider adding 専 as a component of 尃

### ISSUE THREAD

**Issue by mikemorr** [KanjiVG/kanjivg#427]
I'd like to suggest adding <a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/05c02.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05c02.svg" width="50" height="50"> (05c02)</a> as a component of <a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/05c03.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/05c03.svg" width="50" height="50"> (05c03)</a>.

**Comment by benkasminbullock** [comment]
This is added with https://github.com/KanjiVG/kanjivg/commit/02eabf29006930ce22b545002ea7b004f5a491ad. Since the top part was already grouped into one component, it had to be done by splitting into two extra groups.
