### ISSUE TITLE
Cyclical dependencies in dataset

### ISSUE THREAD

**Issue by Fulguritude** [KanjiVG/kanjivg#435]
053b6 厶
0738b 王
07adc 竜
have themselves as a dependency (cycle of length 1).

0620c 戌
0620d 戍
together, have a cyclical dependency of length 2.

These are the only cycles I've found (with an arbitrary length cycle search). I'm not sure if this is intentional or not.

**Comment by benkasminbullock** [comment]
In the top three examples, there is an instance of the element occuring within its own data, but in all three cases that is a "radical" element, so in other words the radical is the character itself. Therefore I think the top three cases are not an issue. In the bottom two I agree with you that there is a cyclic dependency. According to the IDS data, 戌 consists of 戊 enveloping a single stroke, and 戍 is either this construction or another one with 人 on the left, so I think what we should do is to modify those two characters. For the sake of simplicity I will use  戊 as the parent element for both cases.

**Comment by benkasminbullock** [comment]
https://github.com/KanjiVG/kanjivg/commit/ae66a840bbd22e69375ec012b355c93fa675b148 does the things described in the previous comment.
