### ISSUE TITLE
Possible font for obscure kanji/radicals ?

### ISSUE THREAD

**Issue by Fulguritude** [KanjiVG/kanjivg#436]
I found the following in the dataset, but I haven't found a font capable of representing them. I was wondering if you knew of any font capable of handling these ?

'𤴡'
'𢆉'
'𪪷'
'𤍾'
'𦔮'
'𠩺'
'𡕰'
'𢆶'
'𩾏'
'𥝢'
'𣬉'
'𬀷'
'𧒑'

**Comment by benkasminbullock** [comment]
I'm not sure I follow. They are all visible in the github window, so whatever computer I am using seems to have the correct fonts to view them. We don't have information for them in KanjiVG yet though. I assume they could be constructed using something like Inkscape, followed by postprocessing to put them in the correct format, or someone good at programming SVG data could directly create them from the SVGs of KanjiVG itself. I think that Dr Apel originally used Adobe Illustrator to create the graphics.

**Comment by benkasminbullock** [comment]
These display on Google Chrome in Microsoft Windows. I couldn't work out what font is being used by Chrome but pasting into Microsoft Word I found that they are in the font PMingLiU-ExtB, but that doesn't seem to be downloadable. I can't see them in FreeBSD in Gnome Terminal or Emacs, they just show up as boxes. Have you tried downloading the Google fonts which supposedly cover all of Unicode?

**Comment by benkasminbullock** [comment]
I hope this discussion was somewhat helpful.
