### ISSUE TITLE
Upgrade to SVG 1.1

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#458]
Several users have reported problems with parsing the current versions of KanjiVG with various parser software. The central issue seems to be that KanjiVG uses the SVG 1.0 standard, but many parsers only accept the SVG 1.1 standard. I suggest changing the KanjiVG to use SVG 1.1. This would mean removing the `ATTLIST` text and changing the `kvg:` prefix in tags to `kvg-`. Unless anyone has a better validator, we would be checking against the W3C validator.

**Comment by benkasminbullock** [comment]
Again, unfortunately, this turned out to be another wild goose chase.

The SVG 1.1 standard also allows all of the ATTLIST and specific-namespace elements which are allowed in SVG 1.0. Documentation is here:

https://www.w3.org/TR/SVG11/extend.html

The KanjiVG documents could be validated as SVG 1.1 simply by changing the version in the first lines:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [
```
I also note that when the ATTLIST things which people were insisting should be removed, once removed then all of the KVG-specific parts of the files were rejected by the parser. This is obviously absolutely unacceptable to remove all of the KVG radical, stroke type, and grouping information and the validator gives no reason at all to suggest that any of it is misformatted. 

I think the best thing that can  be done here is to offer a release of the KanjiVG files with all of the KanjiVG-specific attributes stripped out of the files.

**Comment by saroupille** [comment]
I can confirm that by changing the header it works.

I think though there is a UX issue with the w3c validator since when we ask it to check the 1.1 compatibility, it returns an error, even though it adds automatically the doctype tag. I am not sure why though.
