### ISSUE TITLE
Python3 dict array does not have `has_key()` method

### ISSUE THREAD

**Issue by qwegat** [KanjiVG/kanjivg#463]
*(This is the first bug report Issue I send to other people's OSS, so there might be some mistakes / machine translated from Japanese at DeepL)*
I imported this library with Python3 because I saw `Added python3 support` in the description of [latest release](https://github.com/KanjiVG/kanjivg/releases/tag/r20230312), However, as the title of the Issue states, it does not seem to be able to handle the change in the method used to check whether a particular key exists in a dict array, so errors occur when `SvgFileInfo` is `read()`, for example.
**The following three lines** seem to be the ones that should be corrected specifically:
https://github.com/KanjiVG/kanjivg/blob/1343323e62557a078464dbcd02ac956413877cda/kanjivg.py#L404
https://github.com/KanjiVG/kanjivg/blob/1343323e62557a078464dbcd02ac956413877cda/kanjivg.py#L410
https://github.com/KanjiVG/kanjivg/blob/1343323e62557a078464dbcd02ac956413877cda/kanjivg.py#L418

**Comment by benkasminbullock** [comment]
Thank you for the bug report. This should be fixed with 2068cb94dd60b47582143d9d44c398256fe44a04. If it still doesn't work, please reopen this and let us know.
