### ISSUE TITLE
\u7E31 (縱) stroke 15 is backwards

### ISSUE THREAD

**Issue by SlugFiller** [KanjiVG/kanjivg#474]
<a href="https://github.com/KanjiVG/kanjivg/blob/master/kanji/07e31.svg"><img src="https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/07e31.svg" width="327" height="327"></a>

Basically identical to #403

In retrospect, it's my fault for failing to spot it in the first batch

**Comment by benkasminbullock** [comment]
Please check if this fixes the issue and reopen if not:

https://github.com/KanjiVG/kanjivg/commit/92b71a571b33eab53cdceb32f97c59a5b5501f43
