### ISSUE TITLE
Missing official Jouyou characters 剝 (0x525D) and 0x20B9F

### ISSUE THREAD

**Issue by eichhirn** [KanjiVG/kanjivg#49]
剝 (0x525D) and 0x20B9F are given as the main variant in the official jouyou list (other variants are allowed). They are variants of the much more common
剥 (0x5265)
叱 (0x53F1)
The differences are in the pig snout radical 彑 and the spoon radical 匕. For both I couldn't find any match of the required variant in kanjivg.

**Comment by ospalh** [comment]
So now i am confused.
The official Jouyou kanji are 剝, 𠮟, but everybody is using 剥, 叱 instead?

**Comment by mifunetoshiro** [comment]
Ease of access and whatnot. The older forms are in JIS X 0208, the other two aren't. A lot of devices wouldn't be able to render them, plus they've been used for so long now already...

**Comment by ospalh** [comment]
Just to make sure, the fourth stroke, tho one that is different between 𠮟 and 叱, should be draw left-to-right in 𠮟, not right to left as in 叱?

**Comment by mifunetoshiro** [comment]
That's correct.
