### ISSUE TITLE
降 None of the components have kanji

### ISSUE THREAD

**Issue by Gnurou** [KanjiVG/kanjivg#5]

**Comment by benkasminbullock** [comment]
The bottom right part of this character did not have an element, so I've added one in this commit:

https://github.com/KanjiVG/kanjivg/tree/add-0964d

There are no other instances of 夅 in KanjiVG, so I did not need to add it elsewhere.

**Comment by benkasminbullock** [comment]
Closing with 5681b9644c4a2b5771e51678a71617d479e253ea
