### ISSUE TITLE
Move latin letters to full-width range

### ISSUE THREAD

**Issue by eichhirn** [KanjiVG/kanjivg#52]
Latin letters from the normal range (00020-...) should be moved to the full-width range (0FF00-...), since they graphically represent full-width characters, being drawn on a square canvas. The normal range should be abandoned.

**Comment by ospalh** [comment]
I love Python.
I did the copying bit, #106

**Comment by ospalh** [comment]
@leehericks:
> 2) Creating/modifying the letters to create half width characters means halving the canvas size of those characters.

I wrote another [Python script](https://gist.github.com/ospalh/fe2ade6f746ceec9e627) and copied the katakana to the halfwidth files. What is missing is actually halving their width. Here i needed a bit of cut-and-pasting,  [`pr`](https://www.gnu.org/software/coreutils/manual/html_node/pr-invocation.html) and sourcing shell commands, because there isn’t really a mapping between normal and half-width katakana.

**Comment by ospalh** [comment]
Then again, unless people [convince me](https://groups.google.com/forum/#!forum/kanjivg) that the half width forms are still useful, i won’t bother to actually reduce the width.

**Comment by ospalh** [comment]
I pulled the full width rōmaji letters, but will not do the half-width katakana, as that would involve too much work.

**Comment by leehericks** [comment]
Apologies on a late reply, now closed. However, from what I followed the kana are now in their proper range of unicode, and we are not interested in creating half-width characters at the moment, which is fair enough.

However, if "I pulled the full width rōmaji letters" means you deleted them from the project then I don't think that was a wise decision. To be fair, my main interest is in the kanji, kana, and punctuation that make up the main usage of Japanese. But various organizations, acronyms, etc. use full-width roman letters. It's just nice to be able to create a full Japanese sentence using the data of KanjiVG.

If I'm misunderstanding, don't mind me.

**Comment by ospalh** [comment]
No, i merged them. I had opened the *pull* request #106, and i used “pulled” to mean “merged the pull request”. 

The full width characters became part of KanjiVG just now.

(I guess with them and the fixes, #102, for #99, it’s time for a new release.)

**Comment by leehericks** [comment]
I see, many thanks for your hard work!

**Comment by ospalh** [comment]
If anybody wants to work on the half-width katakana, they can use [this branch](https://github.com/ospalh/kanjivg/tree/feature-half-width-kana) as a starting point.
