### ISSUE TITLE
Stroke/type mismatch for 丱

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#63]
Looks like there is a consistent inconsistency between the stroke order (numbers and stroke vector data) and the stroke types inside the SVGs for all occurrences of the 丱 element:
For the right side, what is shown is vertical (the rightmost stroke) horizontal vertical (left of the group).
But the `kvg:type` attribute is  `"㇑"`, `"㇑"`, `"㇐"`, that is vertical, vertical, horizontal.
I have no idea what the correct order is. Maybe both are allowed. (And Google is not your friend, as many sites use the kanjivg data.)
It [looks like](http://www.yellowbridge.com/chinese/character-stroke-order.php?searchChinese=1&zi=%E4%B8%B1) the Chinese write this from left to right, vertical, vertical horizontal.

`grep` gave me this list of files:

```
04e31.svg
05618-Jinmei.svg
0589f-HzFstLeRi.svg
0589f-HzFstRiLe.svg
0589f.svg
0589f-VtFstRiLe.svg
06b54-HzFstLeRi.svg
06b54-HzFstRiLe.svg
06b54.svg
06b54-VtFstRiLe.svg
0806f-Kaisho.svg
0806f-KaishoVt3.svg
0806f.svg
095dc-Kaisho.svg
095dc.svg
```

**Comment by coredumper** [comment]
The commit above fixes the stroke types for the three erroneous files returned by `git grep 丱`.

**Comment by ospalh** [comment]
I think `04e31.svg`, `095dc-Kaisho.svg`, `0589f-VtFstRiLe.svg` `0589f-HzFstRiLe.svg` still need fixing.

**Comment by benkasminbullock** [comment]
I've visually inspected all of the 05618, all of the 06b54, all of the 0806f, and all of the 095dc and I've spot checked the source SVG of one file from each of these sets, as well as checking with the multicoloured stroke approach I used in my kanjivg viewer. I don't see any evidence that there is anything wrong with the 丱 element in any of these files.
