### ISSUE TITLE
竹 as top element

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#79]
筆 the 6th stroke is incorrect.

**Comment by ospalh** [comment]
Now i don’t understand this. For #91 you said the standard handwriting version was OK, now you you want to change it?
Also, there is about a ton (123 + variants) of kanji with a reduced 竹 at the top. Did i miss something or did you change all of them?

**Comment by coredumper** [comment]
> Now i don’t understand this. For #91 you said the standard handwriting version was OK, now you you want to change it?

Well, so far I am only fixing open tickets to get acquainted with the project. My comment on #91 was a genuine and innocent question, you may want to reopen it if you believe this needs more attention.

> Also, there is about a ton (123 + variants) of kanji with a reduced 竹 at the top. Did i miss something or did you change all of them?

Err... No, the description only mentioned this kanji, which made me think it was an easy one to begin with.

**Comment by ospalh** [comment]
@coredumper :
So, do you have an opinion on the direction of these stroke 6s? If you are OK with the current state i want to close this.
