### ISSUE TITLE
Question: why does 環 not have a grouping based on 衣 with the kvg:partial attribute?

### ISSUE THREAD

**Issue by fasiha** [KanjiVG/kanjivg#87]
I see a number of kanji with 𧘇 (part of 衣) where those four strokes are in a group with `kvg:element="衣" kvg:partial="true"`: 俵, 喪, 園, 猿, 薗, 表, 衷, 遠.

Is there an etymological/linguistic reason why 環 is not among these? Put another way, why are the last four strokes of 環 just stand-alone `<path>`s and not put in a `<g kvg:element="衣" kvg:partial="true" ...>` group?

(Major kudos and many thanks for KanjiVG. I'm using it in my kanji studies and trying to learn how exactly you have gone about structuring the data as you have, hence this question (and others).)

**Comment by benkasminbullock** [comment]
I tend to disagree with @Gnurou here, I think this is an omission. Further to that I notice the following:

There are five kanji in KanjiVG which contain the 睘 (U+7758) element, which are 

* 鬟
* * kanji/09b1f.svg - does not contain 睘
* * kanji/09b1f-HzFst.svg - does not contain 睘
* 圜
* * kanji/0571c.svg - does not contain 睘
* 環
* * /kanji/074b0.svg - contains 睘
* * kanji/074b0-VtLst.svg - does not contain 睘
* 寰 
* * kanji/05bf0.svg - does not contain 睘
* * kanji/05bf0-Kaisho.svg - does not contain 睘
* 還
* * kanji/09084.svg - contains 睘

I think all of these should have the 睘 element added and the bottom part should also have 𧘇 in all cases as @fasiha suggests.

**Comment by benkasminbullock** [comment]
This should be fixed completely with https://github.com/KanjiVG/kanjivg/commit/4c4c5d0c493a9a07cc1e8d427a562fc5be751f1d. I'll leave the pull request open for 24 hours in case anyone wants to comment.
