### ISSUE TITLE
随

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#91]
For 随,  0968f.svg, stroke 10 could be higher, stroke 11 start higher.

[Kakijun](http://kakijun.jp/page/1273200.html) has the stroke 10, 11 low like KanjiVG.
Both ways, with stroke 10 above or below the level of stroke 5, seem to be OK. Maybe somebody with too much time can add a variant. Anyway, this seems to be low priority.

**Comment by coredumper** [comment]
What is your concern exactly? I cannot find anything wrong with the current form, and I do not understand why 10 and 11 should be different.

If you give me more information, I can probably take care of this issue.

**Comment by ospalh** [comment]
As i said, (or tried to say,) the concern is that lots of fonts show this with a more normal sized ⻌ element, instead of the reduced height one here. I just thought i should mention it.
Part of why i added it as an issue is that i wanted to here a second opinion. Since that is “nothing wrong” …
