### ISSUE TITLE
27 mistakes

### ISSUE THREAD

**Issue by mifunetoshiro** [KanjiVG/kanjivg#99]
璢 074A2.svg correct stroke order: http://kakijun.jp/page/ru16200.html
澑 06F91.svg correct stroke order: http://kakijun.jp/page/E050200.html
鼇 09F07.svg correct stroke order: http://kakijun.jp/page/kokm24200.html
鼈 09F08.svg correct stroke order: http://kakijun.jp/page/suppon25200.html
絨 07D68.svg swap 8 & 9
嫂 05AC2.svg correct stroke order: http://kakijun.jp/page/soua13200.html
搜 0641C.svg correct stroke order: http://kakijun.jp/page/u_j064200.html
藏 085CF.svg correct stroke order: http://kakijun.jp/page/zou18200.html
臟 081DF.svg correct stroke order: http://kakijun.jp/page/harawata22200.html
贓 08D13.svg correct stroke order: http://kakijun.jp/page/zou22200.html
旆 065C6.svg correct stroke order: http://kakijun.jp/page/haih10200.html
椛 0691B.svg 10 shouldn't cross 11

**Comment by mifunetoshiro** [comment]
禽 079BD.svg: 13 strokes not 12
籬 07C6C.svg: strokes 15 and 16 should be more like 厶

Then, in regards to all kanji with 禸 as an element (禽檎璃離擒漓竊魑黐籬), should the second stroke of 厶 be a bit longer to emphasis it's 2 strokes, not 1? Kakijun.jp doesn't seem to mind... A similar thing was done with kanji with 瓦 as an element, where the 3rd stroke is made a bit longer.

**Comment by ospalh** [comment]
簫 07c2b: There isn’t enough room between strokes 13 and 16 to put the number. I’ll leave that one alone.

**Comment by ospalh** [comment]
竊/07aca.svg: I find that listed as 22 strokes, the way it is now, not 23. But looks like stroke 21 should not cross stroke 20

**Comment by ospalh** [comment]
Great. You do realize that the only time you mention 「魑」 is in the throwaway list in the parentheses in you last comment.
魑 09b51.svg: 21 strokes, not 20

**Comment by ospalh** [comment]
Anyway, see #102.
Unless someone complains i will pull those in a few days.

**Comment by mifunetoshiro** [comment]
Yeah, I guess I forgot 魑, so it was 28 kanji.

Regarding 竊, it seems that 21 should indeed not cross 20, but 厶 should still be 3 strokes, not 2. There is no reason why this one single kanji should go against the standard.

http://www.chise.org/est/view/char/%E7%AB%8A
http://glyphwiki.org/wiki/u7aca

Mincho, Meiryo and Adobe's Source Han Sans JP font render it with 3 as well. 22 strokes is a mistake on kakijun (not the only one).

**Comment by ospalh** [comment]
> Regarding 竊 (07aca.svg) (…) 22 strokes is a mistake on kakijun

… and [mahou.org](http://www.mahou.org/Kanji/6366/), and [these folks](http://kanji.quus.net/kakijyun/5317.htm), and [Wiktionary](https://ja.wiktionary.org/wiki/%E7%AB%8A). (I am not listing unihan, they generally have the two-stroke version. Maybe that’s the Chinese way to write this?)

OK. Looks like there are two variants for this, but 22 strokes is somewhat common. Looks like that one kanji *is* different from the others in your list.

**Comment by mifunetoshiro** [comment]
Ok, I guess it's because the radical 禸 isn't actually part of the kanji, just 冂 and 厶(which is a 2-stroke character). I'm closing this then.
